### ISSUE TITLE
Sort Order of Dropdown Items

### ISSUE THREAD

**Issue by tsawyer** [AllStarLink/Allmon3#110]
On my "@@ Development @@" system some dropdown items appear to sort alphanumerically as stated in the readme and others seem to sort in the order they appear in menu.ini. 

My preference would be to have the dropdown menu items display in the same order and they appear in menu.ini

**Comment by jxmx** [comment]
Example?

**Comment by tsawyer** [comment]
### In order of ini:
```
[ WD6AWP ]
type = menu
All Hubs = #2510,2520,2530
* 2510 Test Hub = 2510
* 2520 Special Events = 2520
* 2530 Socal Hub = 2530
2501 Santiago = 2501
2501 RTCM = 'https://allmon3.wd6awp.us/allmon3/voter.html#2501'
2503 Lukens = 2503
2505 RV There Yet =2505
2509 NewASL = 2509
2521 Blue Ridge = 2521
2523 Black Mtn = 2523
2525 Santa Ynez = 2525
2526 Oat Mtn = 2526
2534 Echolink GW = 2534
25333 Maddy = 25333
25334 Test = 25334
```
<img width="221" alt="Screenshot 2023-04-26 at 8 13 55 PM" src="https://user-images.githubusercontent.com/1526362/234750394-74762382-0e40-4fa6-953f-1cc7368d40f2.png">

### Not in order of ini:
```
[ WB6WTM ]
type = menu
All Nodes = #27437,27438,27439,40811
27437 = 27437
27438 = 27438
27439 = 27439
Voter 27439 = 'https://allmon3.wd6awp.us/allmon3/voter.html#27439'
40811 = 40811
```
<img width="173" alt="Screenshot 2023-04-26 at 8 16 13 PM" src="https://user-images.githubusercontent.com/1526362/234750644-769eaddf-7869-4633-87b4-5fb785e3b090.png">
