### ISSUE TITLE
More complete list of apache modules

### ISSUE THREAD

**Issue by encbar5** [AllStarLink/Allmon3#111]
I kept getting syntax errors in allmon3.conf when trying to restart the apache2 service. Turns out I had to run `a2enmod proxy` and `a2enmod rewrite`. Perhaps these need to be added to the instructions? 
Running on RPI4, Debian 11.4, Apache/2.4.56

**Comment by jxmx** [comment]
Good catch. Will do.

**Comment by jxmx** [comment]
README.md has been updated
