### ISSUE TITLE
My Allmon3 Monitoring Dashboard doesn't display node info

### ISSUE THREAD

**Issue by ds5qdr** [AllStarLink/Allmon3#123]
I installed Allmon3 on Debian bullseye at RPi 3.
not display node info but just node number only as below
![image](https://github.com/AllStarLink/Allmon3/assets/64110724/4f350be0-155a-4adb-97ab-d2f5283be743)

my allmon3.ini is as below
[54866]
host=ds5qdr-dvs.iptime.org
user=admin
pass=llcgi

[548750]
host=ds5qdr-fst.iptime.org
user=admin
pass=llcgi

[548751]
host=192.168.0.13
user=admin
pass=llcgi

[548752]
host=192.168.0.13
user=admin
pass=llcgi

[548753]
host=192.168.0.15
user=admin
pass=llcgi

plz give me tips how to fix it.

Thanks,
DS5QDR Heonmin Lee.

**Comment by jxmx** [comment]
@ds5qdr - Please provide any errors in `/var/log/daemon.log` and/or `/var/log/apache2/error.org`.

**Comment by ds5qdr** [comment]
> @ds5qdr - Please provide any errors in `/var/log/daemon.log` and/or `/var/log/apache2/error.org`.
Thanks for reply,

/var/log/daemon.log is below
May 24 21:18:05 Allmon3 dhcpcd[488]: eth0: leased 192.168.0.18 for 7200 seconds
May 24 21:18:05 Allmon3 avahi-daemon[390]: Joining mDNS multicast group on interface eth0.IPv4 with address 192.168.0.18.
May 24 21:18:05 Allmon3 avahi-daemon[390]: New relevant interface eth0.IPv4 for mDNS.
May 24 21:18:05 Allmon3 avahi-daemon[390]: Registering new address record for 192.168.0.18 on eth0.IPv4.
May 24 21:18:05 Allmon3 dhcpcd[488]: eth0: adding route to 192.168.0.0/24
May 24 21:18:05 Allmon3 dhcpcd[488]: eth0: adding default route via 192.168.0.1
May 24 21:18:05 Allmon3 dhcpcd[488]: forked to background, child pid 712
May 24 21:18:05 Allmon3 systemd[1]: Started DHCP Client Daemon.
May 24 21:18:05 Allmon3 systemd[1]: Reached target Multi-User System.
May 24 21:18:05 Allmon3 systemd[1]: Starting Update UTMP about System Runlevel Changes...
May 24 21:18:05 Allmon3 systemd[1]: systemd-update-utmp-runlevel.service: Succeeded.
May 24 21:18:05 Allmon3 systemd[1]: Finished Update UTMP about System Runlevel Changes.
May 24 21:18:05 Allmon3 systemd[1]: Startup finished in 2.079s (kernel) + 15.960s (userspace) = 18.039s.
May 24 21:18:06 Allmon3 systemd[1]: Created slice User Slice of UID 1000.
May 24 21:18:06 Allmon3 systemd[1]: Starting User Runtime Directory /run/user/1000...
May 24 21:18:06 Allmon3 systemd[1]: Finished User Runtime Directory /run/user/1000.
May 24 21:18:06 Allmon3 systemd[1]: Starting User Manager for UID 1000...
May 24 21:18:07 Allmon3 systemd[719]: Queued start job for default target Main User Target.
May 24 21:18:07 Allmon3 systemd[719]: Created slice User Application Slice.
May 24 21:18:07 Allmon3 systemd[719]: Reached target Paths.
May 24 21:18:07 Allmon3 systemd[719]: Reached target Timers.
May 24 21:18:07 Allmon3 systemd[719]: Listening on GnuPG network certificate management daemon.
May 24 21:18:07 Allmon3 systemd[719]: Listening on GnuPG cryptographic agent and passphrase cache (access for web browsers).
May 24 21:18:07 Allmon3 systemd[719]: Listening on GnuPG cryptographic agent and passphrase cache (restricted).
May 24 21:18:07 Allmon3 systemd[719]: Listening on GnuPG cryptographic agent (ssh-agent emulation).
May 24 21:18:07 Allmon3 systemd[719]: Listening on GnuPG cryptographic agent and passphrase cache.
May 24 21:18:07 Allmon3 systemd[719]: Reached target Sockets.
May 24 21:18:07 Allmon3 systemd[719]: Reached target Basic System.
May 24 21:18:07 Allmon3 systemd[719]: Reached target Main User Target.
May 24 21:18:07 Allmon3 systemd[719]: Startup finished in 386ms.
May 24 21:18:07 Allmon3 systemd[1]: Started User Manager for UID 1000.
May 24 21:18:07 Allmon3 systemd[1]: Started Session 1 of user pi.
May 24 21:18:07 Allmon3 systemd[1]: Started Session 3 of user pi.
May 24 21:18:07 Allmon3 systemd[1]: systemd-rfkill.service: Succeeded.
May 24 21:18:07 Allmon3 bthelper[759]: Changing power off succeeded
May 24 21:18:07 Allmon3 bthelper[643]: Changing power on succeeded
May 24 21:18:12 Allmon3 dhcpcd[712]: eth0: no IPv6 Routers available
May 24 21:18:22 Allmon3 systemd[1]: Started Session 4 of user pi.
May 24 21:18:23 Allmon3 systemd[1]: systemd-fsckd.service: Succeeded.
May 24 21:18:47 Allmon3 systemd[1]: systemd-hostnamed.service: Succeeded.

/var/log/apache2/error.log is below
[Wed May 24 21:16:54.420686 2023] [mpm_event:notice] [pid 2447:tid 4153101888] AH00489: Apache/2.4.56 (Raspbian) configured -- resuming normal operations
[Wed May 24 21:16:54.421079 2023] [core:notice] [pid 2447:tid 4153101888] AH00094: Command line: '/usr/sbin/apache2'
[Wed May 24 21:17:51.308359 2023] [mpm_event:notice] [pid 2447:tid 4153101888] AH00492: caught SIGWINCH, shutting down gracefully
[Wed May 24 21:17:55.934593 2023] [mpm_event:notice] [pid 555:tid 4160056896] AH00489: Apache/2.4.56 (Raspbian) configured -- resuming normal operations
[Wed May 24 21:17:55.935989 2023] [core:notice] [pid 555:tid 4160056896] AH00094: Command line: '/usr/sbin/apache2'
[Wed May 24 21:18:52.278071 2023] [proxy:error] [pid 561:tid 4075779072] (111)Connection refused: AH00957: http: attempt to connect to 127.0.0.1:16080 (localhost:16080) failed
[Wed May 24 21:18:52.278292 2023] [proxy_http:error] [pid 561:tid 4075779072] [client 192.168.0.10:51477] AH01114: HTTP: failed to make connection to backend: localhost, referer: http://192.168.0.18/allmon3/index.html

**Comment by ds5qdr** [comment]
sudo systemctl restart allmon3 
![image](https://github.com/AllStarLink/Allmon3/assets/64110724/27eaef9b-8b42-428a-9390-8c9737778d8e)

**Comment by jxmx** [comment]
Those errors indicate that your configuration in `allmon3.ini` for the admin host, port, user, or password is incorrect. You can run it from the command line with `allmon3 --debug` for more information.

**Comment by ds5qdr** [comment]
ASL node 54866 : internal IP : 192.168.0.11
Allmon3 internal IP : 192.168.0.18

at 54866 node, allmon.ini.php is 
<?php
[54866]
host=127.0.0.1:5038
user=admin
passwd=llcgi
nomenu=no
hideNodeURL=no
?>
![image](https://github.com/AllStarLink/Allmon3/assets/64110724/0210cf77-cf4e-4bec-b6f5-63faf1e22595)



allmon3.ini is
[54866]
host=192.168.0.11
user=admin
pass=llcgi

command 
allmon3 --debug
![image](https://github.com/AllStarLink/Allmon3/assets/64110724/1804c644-0ca0-451b-a463-2deb248e7a39)
![image](https://github.com/AllStarLink/Allmon3/assets/64110724/737f6508-cec0-41ae-a3bd-2f449be5e01d)

**Comment by jxmx** [comment]
First off, it looks like you have multiple allmon3 instances running. Make sure all of them are stopped before running one in the foreground with --debug.

Secondly, what is the output of `nc 192.168.0.11 5038`?

**Comment by ds5qdr** [comment]
pi@Allmon3:/etc/allmon3 $ sudo systemctl stop allmon3
pi@Allmon3:/etc/allmon3 $ allmon3 --debug
![image](https://github.com/AllStarLink/Allmon3/assets/64110724/2c410688-946c-4863-8367-809edb48fbd3)

nc localhost 5038
![image](https://github.com/AllStarLink/Allmon3/assets/64110724/20d119ab-096b-4c4b-b6dd-f070ea72f90c)

thanks.

**Comment by jxmx** [comment]
Sorry `nc 192.168.0.11 5038` -- the one that's failing above.

**Comment by ds5qdr** [comment]
![image](https://github.com/AllStarLink/Allmon3/assets/64110724/e15342d7-fc18-4029-a7b3-7e328e1289e5)

![image](https://github.com/AllStarLink/Allmon3/assets/64110724/ca689d24-f7e3-4c9b-b5e0-d7395a841137)

**Comment by jxmx** [comment]
So that looks like the host at 192.168.0.11 is not responding to the host you're connecting from on port 5038. That looks like you have some sort of firewall rule or IP ACL blocking it.

**Comment by jxmx** [comment]
You should get something back like you referenced above saying it's an Asterisk Call Manager service.

**Comment by ds5qdr** [comment]
Thank you for your quick reply.

IP 192.168.0.11 is installed with
Bullseye_Beta_DVSwitch-Server-AllStar-lite.img from dvswitch,org 

I will check it again.
Thanks

DS5QDR Heonmin Lee.

**Comment by jxmx** [comment]
Since localhost seems to work, I'd suggest setting up a single node configuration using what ever node you have configured localhost of the allmon3 host, get that working, and try to add more.

**Comment by ds5qdr** [comment]
Thank you.

I'll try it tomorrow and get back to you.

Thank you again.

**Comment by ds5qdr** [comment]
I tried many different ways, but I haven't succeeded yet.
All four buttons below also operate normally.
![image](https://github.com/AllStarLink/Allmon3/assets/64110724/9f3704cb-b437-4f44-90e1-42eef4c57459)

However, only the Note Status is not extended.

at the Log file, it works fine.
![image](https://github.com/AllStarLink/Allmon3/assets/64110724/652027f8-37e0-436c-a291-db5ade72f119)

I will try again!

Thanks.

**Comment by ds5qdr** [comment]
allmon3 --debug
![image](https://github.com/AllStarLink/Allmon3/assets/64110724/13c325b6-d2a9-4942-a5d0-e67a5aa1096c)

**Comment by jxmx** [comment]
Do you get status output if, with allmon3 running, you do `allmon3-status-client localhost 16700`?

**Comment by ds5qdr** [comment]
commend [allmon3-status-client localhost 16700] and result is below
![image](https://github.com/AllStarLink/Allmon3/assets/64110724/4dc668ef-c51c-4176-8f67-ed71d3bd1dca)

**Comment by jxmx** [comment]
@ds5qdr  that's great! That means everything about Allmon3 is working fine. That means it's an issue with your webserver at the point. Can you paste in your webserver configuration for Allmon3? Are there any errors in your Apache error log - presumably `/var/log/apache2/error.log`.

**Comment by ds5qdr** [comment]
Thank you for your reply.
I look forward to solving the problem soon.

The logs below are
upper : /var/log/daemon.log
lower : /var/log/apache2/error.log
![image](https://github.com/AllStarLink/Allmon3/assets/64110724/5a0f5697-bc98-48c3-bfbc-5c49130cacde)

I think apache2 has no error

---------------------------------------------------------------------------------------------------------------------
below is my settings
allmon3.ini
[54866]
host=192.168.0.11
port=5038
user=admin
pass=llcgi

[548751]
host=192.168.0.13
port=5038
user=admin
pass=llcgi

[548752]
host=192.168.0.13
port=5038
user=admin
pass=llcgi

[548753]
host=192.168.0.15
port=5038
user=admin
pass=llcgi

----------------------------------------------
menu.ini
[ DS5QDR ]
type = menu
DS5QDR = 54866
548751 = 548751
548752 = 548752
548753 = 548753

[ Tistory ]
type = single
Tistory = https://ds5qdr-dv.tistory.com/

--------------------------------------------
web.ini
no change from github

thanks,
DS5QDR Heonmin

**Comment by jxmx** [comment]
I need to see your Apache configuration as I mentioned above. Allmon3 is working fine.

**Comment by ds5qdr** [comment]
and you can access my allmon3
http://ds5qdr-dvs.iptime.org:88/allmon3/index.html

**Comment by jxmx** [comment]
You webserver configuration is not working properly. It's not passing along the websocket connections to Allmon3.

![image](https://github.com/AllStarLink/Allmon3/assets/21324335/2ac0518f-ec51-4de4-b4d0-5538b36665c2)

**Comment by ds5qdr** [comment]
![image](https://github.com/AllStarLink/Allmon3/assets/64110724/18bc0ed7-76b7-4482-a50a-d13502893b7d)

Alias /allmon3 /usr/share/allmon3
<Directory /usr/share/allmon3>
        AllowOverride all
        Order allow,deny
        Allow from all
</Directory>

ProxyAddHeaders On
ProxyPreserveHost On
ProxyPass /allmon3/master/ "http://localhost:16080/"
RewriteEngine On
RewriteCond %{HTTP:Upgrade} websocket [NC]
RewriteCond %{HTTP:Connection} upgrade [NC]
RewriteRule "^/allmon3/ws/voter/([0-9]+)" "ws://localhost:$1" [P,L,QSA]

**Comment by ds5qdr** [comment]
You webserver configuration is not working properly. It's not passing along the websocket connections to Allmon3.

pls give me tips
How to solve my configuration errors?

**Comment by jxmx** [comment]
How is traffic getting to your webserver on port 88?

**Comment by ds5qdr** [comment]
port 88 is my route tcp portfowad to allmon3 server 80 port.
There is no problem with Traffic
![image](https://github.com/AllStarLink/Allmon3/assets/64110724/73782d34-c7aa-470f-baad-c02e867b89f0)

**Comment by jxmx** [comment]
Oh, I see the problem. The Apache configuration file isn't getting updated in the source file properly. Change the `RewriteRule` line in your Apache configuration to this:

```
RewriteRule "^/allmon3/ws/([0-9]+)" "ws://localhost:$1" [P,L,QSA]
```

There's a missing change in the source I  need to fix.

**Comment by jxmx** [comment]
Fix added in 8d5a622. Please let me know @ds5qdr if this fixes the issue.

**Comment by ds5qdr** [comment]
sorry, not fixed yet!
![image](https://github.com/AllStarLink/Allmon3/assets/64110724/bea56411-669a-4af5-971d-ad653d491a81)
![image](https://github.com/AllStarLink/Allmon3/assets/64110724/01236818-dc47-4633-a3e3-43ae0a5ddf6d)

**Comment by jxmx** [comment]
Did you restart Apache2? Your webserver is still acting like the old configuration is in place:

```
$ python3 -m websockets ws://ds5qdr-dvs.iptime.org:88/allmon3/ws/16700
Failed to connect to ws://ds5qdr-dvs.iptime.org:88/allmon3/ws/16700: server rejected WebSocket connection: HTTP 404.
```

**Comment by ds5qdr** [comment]
i installed Allmon3 on RaspberryPi 4B and Debian 11 
![image](https://github.com/AllStarLink/Allmon3/assets/64110724/434a1d66-9d03-4589-bf3e-473c1a85b66d)

**Comment by jxmx** [comment]
And there are no errors in /var/log/apache2 at all?

**Comment by ds5qdr** [comment]
node display updated but still error because of websocket connection.
![image](https://github.com/AllStarLink/Allmon3/assets/64110724/839fa30d-7a21-4fd2-981d-995ebfcc2d95)

are there configuration settings of Allmon3?
plz let me know khow to solve this error!

**Comment by jxmx** [comment]
@ds5qdr this is not an Allmon3 problem but it's a webserver configuration problem. As I showed you before:

```
 $ python3 -m websockets ws://ds5qdr-dvs.iptime.org:88/allmon3/ws/16700
Failed to connect to ws://ds5qdr-dvs.iptime.org:88/allmon3/ws/16700: server rejected WebSocket connection: HTTP 404
```

Your Apache webserver listening on port 80 is not properly configured to pass the websocket traffic to allmon3. It's returning HTTP 404 which meaning the websockets are not being rewritten properly. This is that item I pointed out to you above with the `RewriteRule` directive. I would suggest the following:

1.  Review any Allmon3 configuration you put in `/etc/apache2/conf-enabled` or `/etc/apache2/sites-enabled`. Ensure that the configuration matches the **EXAMPLE** in `/usr/share/doc/allmon3/apache.conf`. Most likely you have a stray configuration error somewhere. Please note that `/etc/allmon3/apache.conf` is not by default the controlling configuration file for Apache.

2. Look at `/var/log/apache2/error.log` or, if configured it, an alternative error log file (see `ErrorLog` directive(s) in your Apache configuration)

**Comment by ds5qdr** [comment]
I changed command
 python3 -m websockets ws://localhost:16700/allmon3/ws/16700
 and result is below
 
![image](https://github.com/AllStarLink/Allmon3/assets/64110724/7eda20e1-818d-47b8-a548-57d58992fbad)

I will recheck my configuration of apche2.
thanks

**Comment by jxmx** [comment]
@ds5qdr  - Yes using `ws://localhost:16700` is asking for the data directly from Allmon3 which means the allmon3 service itself is just fine. This is a webserver configuration issue.

**Comment by ds5qdr** [comment]
I changed line 70 of index.js file 

before : const wsurl = `${wsproto}//${wshost}${wsuri}`;
after :  const wsurl = `${wsproto}//${wshost}:${port}${wsuri}`;

and then everything is OK as below ;
![image](https://github.com/AllStarLink/Allmon3/assets/64110724/24fc919f-df18-4138-987d-5c5b86e314e6)

but another isssue is 
internal IP/allmon3   --- > OK
DDNS/allmon3 ---> NG
![image](https://github.com/AllStarLink/Allmon3/assets/64110724/359742cf-9d0f-4077-a5bf-46948d495eca)

I will try again to solve that!

thanks Jason McCormick!

**Comment by jxmx** [comment]
@ds5qdr That is only working for your IP address because when you're hard-coding in the port like that, you're bypassing Apache altogether and going directly to the statmon port. Your change is writing the URL as ws://192.168.0.8:16700 which is pointing to the allmon websocket listener. That works but only for the local IP address. Now with that change here's what's happening in the code:

![image](https://github.com/AllStarLink/Allmon3/assets/21324335/951b06b4-4431-430e-8838-0623555922af)

Now you're trying to contact http://ds5qdr-dvs.iptime.org:88:16700/allmon3/ which will never work because that's an invalid protocol string. The root problem is still that your Apache installation isn't passing through the websocket. You can see it by simply browsing to `http://ds5qdr-dvs.iptime.org:88/allmon3/ws/16700`. You're getting an HTTP 404 "not found" error. If it was working you'd get a weird message about being unable to call a websocket directly.

**Comment by ds5qdr** [comment]
Thank you for your quick reply.
I will try to install Allmon3 again next week and reply again.
Thank you always.

**Comment by jxmx** [comment]
It's not Allmon3 its your webserver. As I've said several times, attach your Apache configuration here and I'll look at it. Everything in `/etc/apache2/sites-enabled` and `/etc/apache2/conf-enabled`.

**Comment by ds5qdr** [comment]
OK I see! Thanks!

**Comment by jxmx** [comment]
@ds5qdr - I think I may have figured out the issue. In your `/etc/apache2/sites-enabled/000-default.conf`, within the `<VirtualHost *:80>` tag, add the statements `RewriteEngine On` and `RewriteEngine Inherit`. I think this is a quirk of how the stock Debian installation for Apache works and I didn't catch it before. If this fixes your problem, I'll have to rethink how the apache configuration works.

Your `/etc/apache2/sites-enabled/000-default.conf` would look like this:
```
<VirtualHost *:80>
        # The ServerName directive sets the request scheme, hostname and port that
        # the server uses to identify itself. This is used when creating
        # redirection URLs. In the context of virtual hosts, the ServerName
        # specifies what hostname must appear in the request's Host: header to
        # match this virtual host. For the default virtual host (this file) this
        # value is not decisive as it is used as a last resort host regardless.
        # However, you must set it for any further virtual host explicitly.
        #ServerName www.example.com

        ServerAdmin webmaster@localhost
        DocumentRoot /var/www/html

        # Available loglevels: trace8, ..., trace1, debug, info, notice, warn,
        # error, crit, alert, emerg.
        # It is also possible to configure the loglevel for particular
        # modules, e.g.
        #LogLevel info ssl:warn

        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined

        # For most configuration files from conf-available/, which are
        # enabled or disabled at a global level, it is possible to
        # include a line for only one particular virtual host. For example the
        # following line enables the CGI configuration for this host only
        # after it has been globally disabled with "a2disconf".
        #Include conf-available/serve-cgi-bin.conf

        RewriteEngine On
        RewriteOptions Inherit
</VirtualHost>
```

**Comment by jxmx** [comment]
I tested this out thoroughly and I'm 99% sure this is your problem. Install v0.11.0 beta which I'm going to release today or tomorrow.

**Comment by ds5qdr** [comment]
Thank you.
My issue is resolved.
Thank you for your efforts.
![image](https://github.com/AllStarLink/Allmon3/assets/64110724/2d3adac9-41ac-4fdd-885d-4cf7486040cd)
