### ISSUE TITLE
Websocket is not available or went away

### ISSUE THREAD

**Issue by tsawyer** [AllStarLink/Allmon3#138]
Lots of nodes are shutdown or go away for valid or invalid reasons. Is there some way the Allmon3 daemon could be notified to attempt a connect when the web server requests access? I'm think having to restart the service is not the best practice to handle this common occurrence.

**Comment by jxmx** [comment]
Do you have logs showing the issues? If the poller is idle and loses the AMI it reconnects. Perhaps there’s a timeout or a race condition you are hitting that I’m not.

On Jun 12, 2023, at 9:28 PM, Tim Sawyer ***@***.***> wrote:

﻿

Lots of nodes are shutdown or go away for valid or invalid reasons. Is there some way the Allmon3 daemon could be notified to attempt a connect when the web server requests access? I'm think having to restart the service is not the best practice to handle this common occurrence.

**Comment by jxmx** [comment]
@tsawyer  - Let me know if you're seeing this **exact** pattern in the your `/var/log/daemon.log`:

```
Jun 17 11:58:36 allmon3 allmon3[5505]: ERROR: (asl_allmon.ami_conn) connection failed to 172.17.16.137:5038: [Errno 111] Connection refused
Jun 17 11:58:36 allmon3 allmon3[5505]: INFO: (asl_allmon.allmon3_ws_status) connection reestablished after 1 retries
Jun 17 11:58:36 allmon3 allmon3[5505]: ERROR: (asl_allmon.ami_conn) asl_cmd_response() OSError: [Errno 9] Bad file descriptor
Jun 17 11:58:36 allmon3 allmon3[5505]: ERROR: (asl_allmon.allmon3_ws_status) received OSError: [Errno 9] Bad file descriptor; trying to reconnect
Jun 17 11:58:37 allmon3 allmon3[5505]: ERROR: (asl_allmon.ami_conn) [Errno 9] Bad file descriptor
```

Notably that a connection file, claims it was re-established, and then immediately again says it has a bad file descriptor. I think there's a race condition in the logic.

**Comment by jxmx** [comment]
#142 is not related.
