### ISSUE TITLE
Create a user settable text and background color for connecting nodes

### ISSUE THREAD

**Issue by tsawyer** [AllStarLink/Allmon3#148]
This feature would allow the user to add the colors of their choice to nodes in **connecting status** to quickly visualize permanent connections that fail. Default colors could be same a connected node.  

### Allmon2 example: 

<img width="824" alt="Screenshot 2023-06-21 at 7 36 19 AM" src="https://github.com/AllStarLink/Allmon3/assets/1526362/41ba68a4-5064-43eb-9eb5-e7472b0fa73a">

**Comment by jxmx** [comment]
```
/* Node connection table stats=Connecting colors */
--am3-conntable-conn-noconn-color: rgba(0,0,0,1);
--am3-conntable-conn-noconn-bg-color: rgba(255,255,255,1);
```
