### ISSUE TITLE
Node Overrides Adds "None"

### ISSUE THREAD

**Issue by tsawyer** [AllStarLink/Allmon3#154]
Web.ini [node-overrides] addes "None" to beginning and end of displayed values.
 
<img width="965" alt="Screenshot 2023-07-08 at 10 21 45 AM" src="https://github.com/AllStarLink/Allmon3/assets/1526362/3cc3e1e3-bee5-460d-9aa3-e69428110c11">

**Comment by tsawyer** [comment]
These are private colocated voter nodes. 

allmon3.ini:
```
[27685]
host=removed
port=removed
user=removed
pass=removed
multinodes=27685,501,505,506,511
voters=501,505,506,511
```

**Comment by jxmx** [comment]
@tsawyer 

As a quick fix because I'm 99% sure I know what this is.... in `/usr/lib/python3/dist-packages/asl_allmon/node_db/__init__.py` change lines 75-76 from:
```
self.node_database[k]['CALL'] = None
self.node_database[k]['LOC'] = None
```
to:
```
self.node_database[k]['CALL'] = str("")
self.node_database[k]['LOC'] = str("")
```

Restart `allmon3` and see if that fixes the issue.

**Comment by jxmx** [comment]
I think this will fix it. It looks like the JSON encoder is translating the null "None" object to actual text "None".

2747d0ef7767332f34a10942f62cda0587bf9830
