### ISSUE TITLE
Conflicting Race Condition Between Signal Handler and AMI Retries Causes Lockups

### ISSUE THREAD

**Issue by tsawyer** [AllStarLink/Allmon3#158]
A site allmon3.wd6awp.us monitors lost power today. The three servers there went down when the UPS failed. Two issues:

1. When the servers went down Allmon3 became slow to respond. The service would not restart or stop. Had to be killed with `kill <processID>`. Top did not show a busy CPU. Once the service was started Allmon3 became responsive again.
2. When the power was restored the servers did not show even with a page reload. Restating the allmon3 service was necessary.

**Comment by jxmx** [comment]
@tsawyer Please provide the logs from `/var/log/daemon.log`.

**Comment by tsawyer** [comment]
Here are some morning hours of the log from that day.

[daemon_allmon.log](https://github.com/AllStarLink/Allmon3/files/12338688/daemon_allmon.log)

**Comment by jxmx** [comment]
@tsawyer Is there anything in the logs that says "exiting on signal" when you trying to shutdown/restart the process? I'd like to see the logs around that event by a few minutes on each side.

**Comment by jxmx** [comment]
>     2. When the power was restored the servers did not show even with a page reload. Restating the allmon3 service was necessary.

Regarding this one, this is by design. Allmon3 on boot tries to connect to the AMI. If it can't, it drops that node completely. That information is logged when it happens. This is to prevent long-running perpetual retries wasting limited site bandwidth and such.

**Comment by tsawyer** [comment]
`grep -B5 -A5 "exiting on signal" daemon.log*`

[iTerm2 Session Aug 16, 2023 at 7:17:45 AM.txt](https://github.com/AllStarLink/Allmon3/files/12360375/iTerm2.Session.Aug.16.2023.at.7.17.45.AM.txt)

**Comment by tsawyer** [comment]
> > ```
> > 2. When the power was restored the servers did not show even with a page reload. Restating the allmon3 service was necessary.
> > ```
> 
> 
> Regarding this one, this is by design. Allmon3 on boot tries to connect to the AMI. If it can't, it drops that node completely. That information is logged when it happens. This is to prevent long-running perpetual retries wasting limited site bandwidth and such.

From an operational perspective that's problematic as servers stop responding for various reasons all the time. Is there some way this condition can be recovered from without restarting the daemon?

**Comment by jxmx** [comment]
> From an operational perspective that's problematic as servers stop responding for various reasons all the time. Is there some way this condition can be recovered from without restarting the daemon?

To be clear, this is only if the AMI node is unreachable when allmon3 is started. There was a problem I was trying to avoid by doing that but I don't remember what it is and may have been earlier on in the code. This particular item is now #160

**Comment by tsawyer** [comment]
One of the servers I support was showing:
<img width="574" alt="Screenshot 2023-09-04 at 7 40 28 AM" src="https://github.com/AllStarLink/Allmon3/assets/1526362/ae1e954d-1714-479b-a6f3-b4cbd4f5b31b">

`grep -i error /var/log/daemon` shows:
```
Sep  4 00:22:37 Allmon allmon3[624747]: INFO: (asl_allmon.allmon3_ws_voter) ConnctionClosed with Error from ('::1', 37640, 0, 0)
Sep  4 00:22:37 Allmon allmon3[624747]: INFO: (asl_allmon.allmon3_ws_voter) ConnctionClosed with Error from ('::1', 57982, 0, 0)
Sep  4 00:26:17 Allmon allmon3[624747]: INFO: (asl_allmon.allmon3_ws_voter) ConnctionClosed with Error from ('::1', 52788, 0, 0)
Sep  4 07:30:23 Allmon allmon3[624747]: WARNING: (asl_allmon.ami_conn) asl_cmd_response() BrokenPipeError
Sep  4 07:30:23 Allmon allmon3[624747]: ERROR: (asl_allmon.ami_parser) asl_cmd() exception <class 'asl_allmon.ami_conn.AMIException'>
Sep  4 07:30:23 Allmon allmon3[624747]: ERROR: (asl_allmon.ami_parser) asl_cmd() message <class 'asl_allmon.ami_conn.AMIException'>
Sep  4 07:30:32 Allmon allmon3[624747]: WARNING: (asl_allmon.ami_conn) asl_cmd_response() BrokenPipeError
Sep  4 07:30:32 Allmon allmon3[624747]: ERROR: (asl_allmon.ami_parser) asl_cmd() exception <class 'asl_allmon.ami_conn.AMIException'>
Sep  4 07:30:32 Allmon allmon3[624747]: ERROR: (asl_allmon.ami_parser) asl_cmd() message <class 'asl_allmon.ami_conn.AMIException'>
Sep  4 07:30:46 Allmon allmon3[624747]: WARNING: (asl_allmon.ami_conn) asl_cmd_response() BrokenPipeError
Sep  4 07:30:46 Allmon allmon3[624747]: ERROR: (asl_allmon.ami_parser) asl_cmd() exception <class 'asl_allmon.ami_conn.AMIException'>
Sep  4 07:30:46 Allmon allmon3[624747]: ERROR: (asl_allmon.ami_parser) asl_cmd() message <class 'asl_allmon.ami_conn.AMIException'>
Sep  4 07:30:46 Allmon allmon3[624747]: WARNING: (asl_allmon.ami_conn) asl_cmd_response() BrokenPipeError
Sep  4 07:30:46 Allmon allmon3[624747]: ERROR: (asl_allmon.ami_parser) asl_cmd() exception <class 'asl_allmon.ami_conn.AMIException'>
Sep  4 07:30:46 Allmon allmon3[624747]: ERROR: (asl_allmon.ami_parser) asl_cmd() message <class 'asl_allmon.ami_conn.AMIException'>
```

**Comment by jxmx** [comment]
@tsawyer  see if this fixes your restart problems

**Comment by tsawyer** [comment]
@jxmx Running it now. Thank you!
