### ISSUE TITLE
Per user control access to nodes

### ISSUE THREAD

**Issue by tsawyer** [AllStarLink/Allmon3#161]
This request is for a simple ACL to allow user IDs access to linking and system commands for selected nodes only. The idea is to appeal to potential Allmon3 sysops that support multiple groups and/or want to have users control individual nodes without giving out access to all the nodes on the Allmon3 site.

**Comment by tsawyer** [comment]
Fyi... people want this.

https://community.allstarlink.org/t/supermon-restricted-access/20387

**Comment by jxmx** [comment]
76b8e7f..90c81a5

**Comment by jxmx** [comment]
@tsawyer - this is implemented initially in develop. See `/etc/allmon3/user-restrictions`.
