### ISSUE TITLE
Observer Dashboard

### ISSUE THREAD

**Issue by jomimota** [AllStarLink/Allmon3#164]
**Describe the request**
It's possible to implement an Observer Dashboard without login or auth log to use fail2ban?

**Comment by jxmx** [comment]
@jomimota I'm not sure I understand this request. Are you asking for a) Allmon3 to manage fail2ban and b) Do that unauthenticated?

**Comment by jomimota** [comment]
Sorry.
To avoid atacks from Web I think there are two alternatives:
a) A public Dashboard without login (Observer Dashboard); 
or, 
b) A fail2ban implementation to protect login;

**Comment by jxmx** [comment]
@jomimota Allmon3 isn't going to turn into a systems management tool. That is the job of Cockpit and other such systems. I think this enhancement should be to ensure that logging is sufficient such that a fail2ban match could be developed.

**Comment by jomimota** [comment]
I agree.
Fail2ban is a good alternative.

**Comment by jxmx** [comment]
@jomimota  The system already emits a log like the following:

```
INFO: (asl_allmon.allmon3_server) invalid login asd:asd from 172.17.16.216
```

Which should be easily monitored for in `/var/log/daemon.log` by fail2ban.

**Comment by jxmx** [comment]
Information exists for crafting of a fail2ban monitors

**Comment by tsawyer** [comment]
Updated... 
```
Sep  4 12:00:01 Allmon allmon3[628691]: INFO: (asl_allmon.allmon3_server) invalid login asfasf:fsafsaf from 47....
```
