### ISSUE TITLE
Support Nginx with Packaging

### ISSUE THREAD

**Issue by amacleod457** [AllStarLink/Allmon3#169]
Hello,
I just came across this repository while searching Github. I am a long-time user of Allmon2, and figured I'd give this a try, as it appears that it will run on Debian 12. However, I have long-ago switched away from Apache2 in favour of Nginx.
I read in one of the changelogs that things were made easier for Nginx users, but documentation in this repo seems to remain scant at this point in pre-release.
So I am writing to ask how I might go about deploying Allmon3 in an Nginx environment?
Thank you for all your hard work.

**Comment by jxmx** [comment]
At the moment, Nginx is not officially supported with the packaging however it will work just fine. For Allmon3, you just need to translate the configuration in [allmon3.conf](https://github.com/AllStarLink/Allmon3/blob/develop/conf/allmon3.conf) to NGinx specific directives. Functionally, you'll need support of rewriting, websockets, and reverse proxying of websockets.

**Comment by amacleod457** [comment]
Ok, awesome. Thank you.

**Comment by jxmx** [comment]
@amacleod457 this is fixed in  d4967fc..ad17f0f and will be included in v1.0.2
