### ISSUE TITLE
Insecure links

### ISSUE THREAD

**Issue by Pross** [AllStarLink/Allmon3#173]
**Describe the bug**
There are a few (4) insecure http links in the code which get a pointless redirection to https 

**Expected behavior**
All external links should be https

_M7DHQ_

**Comment by jxmx** [comment]
@Pross - None of the URLs in your pull request have automatic redirection to TLS.

**Comment by Pross** [comment]
Of course they do ;) Example:
```
curl -v http://deb.debian.org/debian
*   Trying 146.75.74.132:80...
* Connected to deb.debian.org (146.75.74.132) port 80 (#0)
> GET /debian HTTP/1.1
> Host: deb.debian.org
> User-Agent: curl/8.1.2
> Accept: */*
>
< HTTP/1.1 302 Found
< Connection: keep-alive
< Content-Length: 277
< Server: Apache
< X-Content-Type-Options: nosniff
< X-Frame-Options: sameorigin
< Referrer-Policy: no-referrer
< X-Xss-Protection: 1
< Permissions-Policy: interest-cohort=()
< Location: http://ftp.debian.org/debian/
< Content-Type: text/html; charset=iso-8859-1
< Via: 1.1 varnish, 1.1 varnish
< Accept-Ranges: bytes
< Date: Wed, 18 Oct 2023 19:39:17 GMT
< Age: 0
< X-Served-By: cache-ams21054-AMS, cache-lcy-eglc8600035-LCY
< X-Cache: HIT, MISS
< X-Cache-Hits: 1, 0
< X-Timer: S1697657957.195400,VS0,VE10
<
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>302 Found</title>
</head><body>
<h1>Found</h1>
<p>The document has moved <a href="http://ftp.debian.org/debian/">here</a>.</p>
<hr>
<address>Apache Server at ftp.debian.org Port 80</address>
</body></html>
* Connection #0 to host deb.debian.org left intact
```

**Comment by Pross** [comment]
Also, in the readme file, one of the deb links is http ( the one I fixed ) later on in the file its https ;)

**Comment by jxmx** [comment]
For debian the `/debian/` subdir redirects but the overall site does not. However the other links at allstarlink.org definitely do not.

**Comment by Pross** [comment]
> For debian the `/debian/` subdir redirects but the overall site does not. However the other links at allstarlink.org definitely do not.

The allstar links do when opened in a browser like chrome that automatically tries to upgrade you to ssl if its offered by the server. Browsers do intend and are making it harder to use http:// these days, you get a "This site is insecure" message and you have to click to acknowledge.

**Comment by jxmx** [comment]
I understand all that. However hard-coding that is presumptive of a remote site that has chosen - purposefully or not - not to force redirections to TLS-encrypted connections. That is the function of HTTP redirections, or preferably, the HSTS header in the HTTP protocol. There's also non-trivial load considerations to TLS connection termination and support for busy systems on small servers like ASL. I'll talk to the ASL web people about their thoughts on forcing TLS before I commit that code.
