### ISSUE TITLE
Locally Hosted Allmon Crashes

### ISSUE THREAD

**Issue by tsawyer** [AllStarLink/Allmon3#177]
Allmon3 has been dying repeatedly today. `systemctl restart allmon3` makes it run for a while.

Strange thing is the voter display works but not the nodes display. Server is at http://45.63.56.86/allmon3/

I don't see a daemon log file on this Vultr VM. But journalctl has a bunch of errors and info that should be helpful. 

Captured this with `journalctl -u allmon3 | cat > allmon3.log`
[allmon3.log](https://github.com/AllStarLink/Allmon3/files/13210243/allmon3.log)

**Comment by jxmx** [comment]
@tsawyer - Looking at this all I see is the underlying AMI on 127.0.0.1:5038 flapping and then something eventually restarting the allmon3 process. I also note this is the old code before I cleaned it up with the asynchronous stream code.
