### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by travnewmatic** [AllStarLink/Allmon3#178]
I'm attempting to create a Dockerfile for allmon3

This is what I've come up with so far:
```
FROM debian:bookworm-slim
RUN apt update && apt install -y gpg apache2 python3-websockets python3-argon2 python3-aiohttp python3-aiohttp-session wget
RUN wget https://github.com/AllStarLink/Allmon3/releases/download/rel_t_1_0_1/allmon3_1.0.1-1_all.deb && \
  apt install -y ./allmon3_1.0.1-1_all.deb
ENTRYPOINT ["/usr/bin/allmon3"]
```
The `.deb` installs without issue.

To run it, I execute something like this:
`docker run -it --network=host --name=allmon3 -v ./allmon3.ini:/etc/allmon3/allmon3.ini allmon3`

Here is my `allmon3.ini`:
```
[59913]
host=192.168.100.19
port=5038
user=admin
pass=llcgi
```
My `asl` node is running on a raspberry pi separately.  Asterisk is listening on `0.0.0.0`.  Previously I saw an error that indicated it was unable to connect to asterisk.

Unfortunately, I dont get anything when I browse to `localhost:16080`, all I get is the text `404: Not Found`:
![image](https://github.com/AllStarLink/Allmon3/assets/11083305/88fa8454-6113-43e3-a844-0165c3220181)

This appears to be from the python webserver, not the browser.

Here are the logs when my container comes up:
```
DEBUG: (allmon3) config file is /etc/allmon3/allmon3.ini                                                                                      
DEBUG: (asl_allmon.node_configs) nodes_on_host: 1                                                                                             
DEBUG: (allmon3) web config file is /etc/allmon3/web.ini                                                                                      
INFO: (asl_allmon.web_configs) Allmon3 Master HTTP port is 16080                                                                              
INFO: (asl_allmon.web_configs) Allmon3 websockets starting port is 16700                                                                      
INFO: (asl_allmon.web_configs) Binding sevices to all addresses                                                                               
INFO: (allmon3) no %s found; no menu data available                                                                                           
DEBUG: (allmon3) user_table file is /etc/allmon3/users       
DEBUG: (allmon3) restriction_table file is /etc/allmon3/user-restrictions
DEBUG: (asl_allmon.security) loaded 1 entries from /etc/allmon3/users
DEBUG: (asl_allmon.security) loaded 0 entries from /etc/allmon3/user-restrictions
DEBUG: (asl_allmon.node_db) entering get_allmon_db()         
INFO: (asl_allmon.node_db) Retrieving database from https://allmondb.allstarlink.org/
INFO: (asl_allmon.node_db) Updated node database in 6.24 seconds
DEBUG: (asl_allmon.node_db) exiting getAllMonDB()                                                                                             
DEBUG: (asl_allmon.node_db) entering add_node_overrides()    
DEBUG: (asl_allmon.node_db) exiting add_node_overrideS()                                                                                      
DEBUG: (asl_allmon.node_db) entering set_my_info()           
DEBUG: (asl_allmon.node_db) exiting set_my_info()                                                                                             
DEBUG: (allmon3) starting the main work loop                 
DEBUG: (allmon3) enter start_tasks()                                                                                                          
INFO: (allmon3) starting status ws 59913@192.168.100.19 on port 16700
INFO: (allmon3) starting cmd ws 59913@192.168.100.19 on port 16701
INFO: (allmon3) starting allmon3 master ws on port 16080
INFO: (allmon3) starting node_db updater
DEBUG: (asl_allmon.allmon3_ws_status) enter node_status_main(59913)
DEBUG: (asl_allmon.ami_conn) asl_create_connection()
DEBUG: (asl_allmon.ami_conn) connect() using 192.168.100.19:5038
DEBUG: (asl_allmon.ami_conn) AIM version: Asterisk Call Manager/1.0
DEBUG: (asl_allmon.ami_conn) enter asl_cmd_response()
DEBUG: (asl_allmon.ami_conn) command >> ACTION: LOGIN USERNAME: admin SECRET: llcgi EVENTS: 0  ActionID: 112c8070-da43-4436-85fb-5eb4a7292a0e
INFO: (asl_allmon.allmon3_ws_cmd) server listening on [::]:16701
INFO: (asl_allmon.allmon3_ws_cmd) server listening on 0.0.0.0:16701
DEBUG: (asl_allmon.ami_conn) response >> Response: Success  Message: Authentication accepted                                                  
DEBUG: (asl_allmon.ami_conn) Response: Success Message: Authentication accepted  
DEBUG: (asl_allmon.ami_conn) leaving asl_create_connection()
INFO: (asl_allmon.allmon3_ws_status) server listening on [::]:16700
INFO: (asl_allmon.allmon3_ws_status) server listening on 0.0.0.0:16700
INFO: (asl_allmon.allmon3_ws_status) broadcasting status for 59913 on port 16700
DEBUG: (asl_allmon.allmon3_ws_status) enter node_status_broadcast()
DEBUG: (asl_allmon.allmon3_ws_status) Node 59913: status_connections: 0 
DEBUG: (asl_allmon.allmon3_ws_status) status asyncio.sleep(1)
DEBUG: (asl_allmon.allmon3_ws_status) Node 59913: status_connections: 0 
DEBUG: (asl_allmon.allmon3_ws_status) status asyncio.sleep(1)
DEBUG: (asl_allmon.allmon3_ws_status) Node 59913: status_connections: 0 
DEBUG: (asl_allmon.allmon3_ws_status) status asyncio.sleep(1)
```

I feel like I'm pretty close to making this work.  Do you have any suggestions?  Thanks!

KJ5DCL

**Comment by jxmx** [comment]
Allmon3 is not a designed to operate as a containerized app and isn't a full-blown webserver on 16080 - it's socket API only. If you want to install Apache into the container and run it on an alternative port that probably would work.

**Comment by travnewmatic** [comment]
Thanks for the response!

More likely I would run a separate Apache container in tandem with Allmon3.

I was looking in your repo for some Apache config to act as a reverse proxy in front of Allmon3 but couldn't find anything.

I would assume that the existing Apache config would work just by changing where its looking for Allmon3, different hostname or ip instead of localhost:16080.

In what regard is it 'not designed to operate as a containerized app?'  should i quit while i'm ahead?

**Comment by tsawyer** [comment]
Ports need to be exposed to the world outside of the container. Also, the internal ports can stay where they while mapping the internal port to another external port.

**Comment by travnewmatic** [comment]
mmm alright, what are the internal/external ports youre referring to?  if we're just talking about allmon3, i see 16080 for HTTP and 16700 for WebSockets.

as far as Allmon3 needing to interact with asl/asterisk, is it only port 5038 or are there others?

may i get a working apache config that i could use as a reference?

**Comment by travnewmatic** [comment]
i found the apache config you're using in your .deb

```
# cat /etc/apache2/conf-enabled/allmon3.conf
##
## Configuration for the allmon3 application
##

Alias /allmon3 /usr/share/allmon3

<Directory /usr/share/allmon3>
        AllowOverride all

    # Implement rewrite within the directory so that is survives
    # into the <VirtualHost> tags
    RewriteEngine On
    RewriteCond %{HTTP:Upgrade} =websocket [NC]
    RewriteRule ^ws/([0-9]+) ws://localhost:$1 [P,L,QSA]
</Directory>

# Proxy can't usefully occur inside a <Directory> on Debian
ProxyAddHeaders On
ProxyPreserveHost On
ProxyPass /allmon3/master/ "http://localhost:16080/"
```
I'll see what I can do with this

**Comment by tsawyer** [comment]
Well, as you have apache and allmon3 in the same container, making them both on the same network, you only need to expose 80. Allmon should be able to access 5038 as that's on your node and external to docker.

Take a look at docker-compose. It's a lot easier to deal with and brings a lot to the table. You still have to build a Dockerfile and image which you can do either with Docker or with docker-compose.

**Comment by travnewmatic** [comment]
i have to make a confession, i'm not so great at managing multiple processes from within a container.

assuming i can make apache serve allmon3 properly, this will likely end up as a deployment (apache + allmon3 in a single pod) in my kubernetes homelab along with the rest of my stuff

**Comment by tsawyer** [comment]
I'm not so great at Docker either or I'd already have done it.

**Comment by travnewmatic** [comment]
i dont think its bad to release an image with the expectation that it needs a separate webserver to go with it.

php-fpm has an official image but thats useless on its own.

i mean, it would be cool if allmon3 could serve a page without needing apache, but to me thats not a deal-breaker.

also i would prefer to have only a single process running in a container.

**Comment by jxmx** [comment]
Turning Allmon3 into a full webserver is an anti-feature when there are many existing quality webservers people can already leverage. It currently supports Apache and I'm going to add Nginx and Lighttpd. I'm not sure why you'd want to run this in a container when it's designed to be natively installed with minimal and standard-available packages. However if you want to run it in a container itself, you would need the container to expose TCP ports 16080 and 16700 through (16700 + Asterisk instances * 3 - 1) to the webserver (or other custom ports if you change them in `web.ini`).

**Comment by travnewmatic** [comment]
>Turning Allmon3 into a full webserver is an anti-feature when there are many existing quality webservers people can already leverage

I dont have a problem with that, I just wasn't aware that allmon3 required a separate webserver in order to function properly.

>I'm not sure why you'd want to run this in a container when it's designed to be natively installed with minimal and standard-available packages

Because i already have a homelab running kubernetes with all my services inside of it.  Running a single thing on a separate device (in this case a raspberry pi) is inconvenient for a variety of reasons.  If i was running proxmox (or similar) putting asl/allmon3 in a VM would probably be ok, but today i'm running k3s on ubuntu on a physical machine.  I use argocd to manage all my workloads.  the ability to codify and declaratively manage all my services and storage and networking has been a game-changer for me, and i have very little desire to do things 'the old way' if i can avoid it.

actually, my hope is that more ham-related server projects will move toward containers.  it would be amazing if there were a ham-centric 'operating system' like [Home Assistant OS](https://github.com/home-assistant/operating-system) or [TrueNAS SCALE](https://www.truenas.com/truenas-scale/).  Both of those projects run kubernetes under the hood (i believe both use k3s).  both include an 'app store', which is really just a GUI to install helm charts from repositories.  because everything is containerized, nobody steps on anything else and dependency hell is a non-issue.  maybe someday!

> However if you want to run it in a container itself, you would need the container to expose TCP ports 16080 and 16700 through (16700 + Asterisk instances * 3 - 1) to the webserver (or other custom ports if you change them in web.ini).

this'll work! thanks for the info!

**Comment by jxmx** [comment]
I'd welcome a configuration/script to be part of Allmon3 that bundles the Allmon3 part with the webserver part as a single container. That would probably be of interest to some people.

**Comment by travnewmatic** [comment]
Challenge accepted :+1: 

Got a couple of other things on my plate, but this should be pretty straight-forward.

Still doing some brainstorming, But I see two approaches to containerization:

## Option 1: All-in-one image
Not my favorite (does not adhere to Unix philosophy of only doing one thing, but doing that one thing well), but potentially simpler deployment for the end user.  `supervisor` manages starting allmon3 and then apache2.  Because the allmon3 `.deb` package includes static files and apache2 configuration, in addition to the python3 application, this would produce the most 'equivalent' result (functionality in deb = functionality in image)
## Option 2: Separate images for apache2 and allmon3
- `allmon3-web` Dockerfile downloads and installs your .deb, only starts apache2
- `allmon3-python` same as first, but only starts allmon3 (not totally happy with that name, but you get the idea)

While it does require a longer `docker-compose.yaml`, I prefer this method.  It follows the `do one thing and do it well` Unix philosophy and makes for simpler, more understandable Dockerfiles.  This design pattern resembles (among other projects) how Wordpress provides their Docker images.  They do provide all-in-one images including apache and php-fpm, but they also provide images containing just php and just apache.  This is helpful for those wishing to run a different webserver (like nginx), or those wishing to horizontally scale the php process independently of the webserver process.

**Comment by jxmx** [comment]
I would argue nothing about containers adheres to a Unix philosophy. :)  Personally, I do not use them at all for that reason. However if we're going to do containerization, only Option 1 makes sense to me.

**Comment by jxmx** [comment]
Didn't finish my thought.... trying to plumb two containers together seems like a support nightmare.

**Comment by travnewmatic** [comment]
Take a gander https://github.com/AllStarLink/Allmon3/pull/183

lemme know what you think

**Comment by jxmx** [comment]
Added from pull #183
