### ISSUE TITLE
Allmon3 v1.0.1 custom.css Regresson 

### ISSUE THREAD

**Issue by tsawyer** [AllStarLink/Allmon3#180]
Looks like the 1.0.1 release broke these custom.css settings. These setting should the bar green but they no longer have any effect.
```
        /* Node connection table keyed color */
        --am3-conntable-conn-keyed-color: rgba(255, 255, 255, 1);
        --am3-conntable-conn-keyed-bg-color: rgba(12,161,34,0.75);
```

I recommend including these settings as a default. It's something Allmon2 users are used to.

**Comment by jxmx** [comment]
@tsawyer `custom.css` works fine on all my deployments that I can tell. Can you check the following?

1. `/usr/share/allmon3/css/custom.css` is still a symlink to `/etc/allmon3/custom.css`
2. `/etc/allmon3/custom.css` is world-readable and/or readable by the www-data user?

**Comment by jxmx** [comment]
#181

**Comment by tsawyer** [comment]
Both of those look good here. I changed a couple of the initial custom.css successfully. It's only these new ones that don't work.  

```
lrwxrwxrwx 1 root root   23 Jun 17 12:57 custom.css -> /etc/allmon3/custom.css

-rw-r--r-- 1 root root 1.5K Nov  8 06:40 custom.css
```


In addition to the Transmitting colors not working, the Connecting colors are not working either. These settings do not change the colors.

```
        /* Node connection table stats=Transmitting colors */
        --am3-conntable-conn-keyed-color: rgba(255, 255, 255, 1);
        --am3-conntable-conn-keyed-bg-color: rgba(12,161,34,0.75);

        /* Node connection table stats=Connecting colors */
        --am3-conntable-conn-noconn-color: rgba(255,255,255,1);
        --am3-conntable-conn-noconn-bg-color: rgba(241,158,56,1);
```

**Comment by jxmx** [comment]
This appears to have broken with the merge updating Bootstrap.
