### ISSUE TITLE
Implement NodeDB as Thread

### ISSUE THREAD

**Issue by jxmx** [AllStarLink/Allmon3#185]
When the database distribution server is down, the try/except/sleep cycle is locking up all threads. Reimplement the nodedb in a separate asyncio task thread.

**Comment by jxmx** [comment]
@Pross

**Comment by jxmx** [comment]
Use of urllib, sleep, sigusr1 handling, etc. all require blocking which is undesirable

**Comment by jxmx** [comment]
@Pross @tsawyer Please try https://github.com/AllStarLink/Allmon3/releases/tag/rel_t_1_1_0 before I announce it to Community to see if it addresses lagging/lockup issues related to the ASL DB retrieval issues.

**Comment by Pross** [comment]
As far as I can tell it works as expected 
Tx was still showing up while it was retrying tho it didn't know what it was connected to said unknown possibly local or something like that possibly due to the way I disabled dns anyway after the 5 tries it gave up I re-enabled dns and things started working normally again.

**Comment by jxmx** [comment]
So are you saying in your testing the dashboard is still hanging on network issues? What specifically are you doing to test that which causes a lockup?

On Dec 10, 2023, at 2:40 PM, Simon Prosser ***@***.***> wrote:

﻿

As far as I can tell it works as expected
Tx was still showing up while it was retrying tho it didn't know what it was connected to said unknown possibly local or something like that possibly due to the way I disabled dns anyway after the 5 tries it gave up I re-enabled dns and things started working normally again.

**Comment by Pross** [comment]
Retested by commenting out nameservers in resolv.conf, when dns is restarted the db is properly updated.

I think the other glitch was because I restarted allmon3 service while dns was down.

So .. no issues everything works.
