### ISSUE TITLE
Service stopped after an internet failure

### ISSUE THREAD

**Issue by KB4MDD** [AllStarLink/Allmon3#189]
I believe that I had an internet outage on December 10th.  When it came backup, the allmon3.service was not running.

Version 1.01.

Log entries of interest:

Dec 10 14:06:00 wa4tal allmon3[655]: INFO: (asl_allmon.node_db) Updated node database in 1.78 seconds
Dec 10 14:21:00 wa4tal allmon3[655]: INFO: (asl_allmon.node_db) Retrieving database from https://allmondb.allstarlink.org/
Dec 10 14:21:11 wa4tal allmon3[655]: ERROR: (asl_allmon.node_db) Failed to retrieve database with error: <urlopen error [Errno -3] Temporary>
Dec 10 14:21:11 wa4tal allmon3[655]: ERROR: (asl_allmon.node_db) Waiting 5 minutes to try again: attempt 1/5
Dec 10 14:26:11 wa4tal allmon3[655]: INFO: (asl_allmon.node_db) Retrieving database from https://allmondb.allstarlink.org/
Dec 10 14:26:23 wa4tal allmon3[655]: ERROR: (asl_allmon.node_db) Failed to retrieve database with error: <urlopen error [Errno -3] Temporary>
Dec 10 14:26:23 wa4tal allmon3[655]: ERROR: (asl_allmon.node_db) Waiting 5 minutes to try again: attempt 2/5
Dec 10 14:31:23 wa4tal allmon3[655]: INFO: (asl_allmon.node_db) Retrieving database from https://allmondb.allstarlink.org/
Dec 10 14:31:36 wa4tal allmon3[655]: ERROR: (asl_allmon.node_db) Failed to retrieve database with error: <urlopen error [Errno -3] Temporary>
Dec 10 14:31:36 wa4tal allmon3[655]: ERROR: (asl_allmon.node_db) Waiting 5 minutes to try again: attempt 3/5
Dec 10 14:36:36 wa4tal allmon3[655]: INFO: (asl_allmon.node_db) Retrieving database from https://allmondb.allstarlink.org/
Dec 10 14:36:48 wa4tal allmon3[655]: ERROR: (asl_allmon.node_db) Failed to retrieve database with error: <urlopen error [Errno -3] Temporary>
Dec 10 14:36:48 wa4tal allmon3[655]: ERROR: (asl_allmon.node_db) Waiting 5 minutes to try again: attempt 4/5
Dec 10 14:41:48 wa4tal allmon3[655]: INFO: (asl_allmon.node_db) Retrieving database from https://allmondb.allstarlink.org/
Dec 10 14:41:58 wa4tal allmon3[655]: ERROR: (asl_allmon.node_db) Failed to retrieve database with error: <urlopen error [Errno -3] Temporary>
Dec 10 14:41:58 wa4tal allmon3[655]: ERROR: (asl_allmon.node_db) Waiting 5 minutes to try again: attempt 5/5
Dec 10 14:46:58 wa4tal allmon3[655]: INFO: (asl_allmon.node_db) Retrieving database from https://allmondb.allstarlink.org/
Dec 10 14:47:10 wa4tal allmon3[655]: ERROR: (asl_allmon.node_db) Failed to retrieve database with error: <urlopen error [Errno -3] Temporary>
Dec 10 14:47:10 wa4tal allmon3[655]: ERROR: (asl_allmon.node_db) Waiting 5 minutes to try again: attempt 6/5
Dec 10 14:52:10 wa4tal allmon3[655]: INFO: (asl_allmon.allmon3_ws_status) server closing
Dec 10 14:52:10 wa4tal allmon3[655]: Traceback (most recent call last):
Dec 10 14:52:10 wa4tal allmon3[655]:   File "/usr/bin/allmon3", line 247, in <module>
Dec 10 14:52:10 wa4tal allmon3[655]:     asyncio.run(start_tasks())
Dec 10 14:52:10 wa4tal allmon3[655]:   File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
Dec 10 14:52:10 wa4tal allmon3[655]:     return runner.run(main)
Dec 10 14:52:10 wa4tal allmon3[655]:            ^^^^^^^^^^^^^^^^
Dec 10 14:52:10 wa4tal allmon3[655]:   File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
Dec 10 14:52:10 wa4tal allmon3[655]:     return self._loop.run_until_complete(task)
Dec 10 14:52:10 wa4tal allmon3[655]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Dec 10 14:52:10 wa4tal allmon3[655]:   File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
Dec 10 14:52:10 wa4tal allmon3[655]:     return future.result()
Dec 10 14:52:10 wa4tal allmon3[655]:            ^^^^^^^^^^^^^^^
Dec 10 14:52:10 wa4tal allmon3[655]:   File "/usr/bin/allmon3", line 127, in start_tasks
Dec 10 14:52:10 wa4tal allmon3[655]:     raise e
Dec 10 14:52:10 wa4tal allmon3[655]:   File "/usr/bin/allmon3", line 114, in start_tasks
Dec 10 14:52:10 wa4tal allmon3[655]:     await asyncio.gather(*tasks)
Dec 10 14:52:10 wa4tal allmon3[655]:   File "/usr/lib/python3/dist-packages/asl_allmon/node_db/__init__.py", line 82, in db_updater
Dec 10 14:52:10 wa4tal allmon3[655]:     self.get_allmon_db()
Dec 10 14:52:10 wa4tal allmon3[655]:   File "/usr/lib/python3/dist-packages/asl_allmon/node_db/__init__.py", line 45, in get_allmon_db
Dec 10 14:52:10 wa4tal allmon3[655]:     nodedb = re.split(r"\n", dbf)
Dec 10 14:52:10 wa4tal allmon3[655]:                       ^^^^^
Dec 10 14:52:10 wa4tal allmon3[655]: UnboundLocalError: cannot access local variable 'dbf' where it is not associated with a value
Dec 10 14:52:10 wa4tal systemd[1]: allmon3.service: Main process exited, code=exited, status=1/FAILURE
Dec 10 14:52:10 wa4tal systemd[1]: allmon3.service: Failed with result 'exit-code'.
Dec 10 14:52:10 wa4tal systemd[1]: allmon3.service: Consumed 39.457s CPU time.
Dec 12 17:47:29 wa4tal systemd[1]: Starting allmon3.service - Allmon3 daemon...

In viewing the logs, I see these same entries back in November.  So it appeared to have happened before.

Unfortunately, I did not capture the systemctl status allmon3 that showed the service as failed.  It did not appear to automatically restart.

**Comment by jxmx** [comment]
@KB4MDD  can you upgrade to 1.1.0? I believe the problem above was resolved with #185.

**Comment by KB4MDD** [comment]
I have upgraded and will report  back.  I will close for now.
