### ISSUE TITLE
Add supported OS to deb release notes

### ISSUE THREAD

**Issue by jimt** [AllStarLink/Allmon3#190]
**Describe the request**
Please include supported OS release(s) (or other breaking changes) on the [Releases page](https://github.com/AllStarLink/Allmon3/releases/tag/rel_t_1_1_0)

The release note for v1.1.0 does not mention that it is not supported on Debian 10.  That only became obvious after trying to install it, failing, and then checking the revised README.

**Version Info**
v1.1.0

**Comment by jxmx** [comment]
@jimt It is still supported on version 10. That’s my fault for not completely finishing the release. I jumped the gun on drafting the release in GitHub, but was waiting for feedback. I will add the Debian 10 .debs ASAP.

**Comment by jxmx** [comment]
https://github.com/AllStarLink/Allmon3/commit/321fae089d02da79128c5dab6e0cdd31f066a855

**Comment by jimt** [comment]
Thanks.  That one fails with a `ModuleNotFoundError: No module named 'asl_allmon'` error.  I will investigate in the next day or two.
