### ISSUE TITLE
Build Process Broken / Missing pandoc

### ISSUE THREAD

**Issue by jimt** [AllStarLink/Allmon3#194]
**Describe the bug**
allmon3 fails on launch with `ModuleNotFoundError: No module named 'asl_allmon'` #190

**To Reproduce**
1. Install `allmon3_1.1.0-1_deb10.deb`
2. Launch via systemd
3. Check the journal

**Expected behavior**

**Log Information**
```
Dec 21 21:01:53 allstarnz systemd[1]: Starting Allmon3 daemon...
Dec 21 21:01:53 allstarnz systemd[1]: Started Allmon3 daemon.
Dec 21 21:01:53 allstarnz allmon3[67547]: Traceback (most recent call last):
Dec 21 21:01:53 allstarnz allmon3[67547]:   File "/usr/bin/allmon3", line 19, in <module>
Dec 21 21:01:53 allstarnz allmon3[67547]:     from asl_allmon import allmon3_server, allmon3_ws_status, allmon3_ws_cmd, allmon3_ws_voter
Dec 21 21:01:53 allstarnz allmon3[67547]: ModuleNotFoundError: No module named 'asl_allmon'
Dec 21 21:01:53 allstarnz systemd[1]: allmon3.service: Main process exited, code=exited, status=1/FAILURE
Dec 21 21:01:53 allstarnz systemd[1]: allmon3.service: Failed with result 'exit-code'.
```

**Version Info**
1.1.0-1_deb10

**Additional context**

`dpkg -c` says the **deb** file appears to be missing the `/usr/lib/python3/dist-packages/asl_allmon/` tree.

**Comment by jxmx** [comment]
The whole build process is semi-failing due to a missing build depdency

**Comment by jxmx** [comment]
@jimt please try the new purpose-built buster .deb:

https://github.com/AllStarLink/Allmon3/releases/tag/t_rel_1_1_1

**Comment by jimt** [comment]
It installed without issue and seems to be working.

Thanks! :tada:
