### ISSUE TITLE
Decide/implement if it's worth checking the ActionID for commands

### ISSUE THREAD

**Issue by jxmx** [AllStarLink/Allmon3#2]
I haven't yet been able to cause any of the commands to respond out-of-order but it's theoretically possible...

**Comment by tsawyer** [comment]
I'd say that is a definite requirement with any AMI implementation. You never know what other apps will be accessing the AMI.

**Comment by jxmx** [comment]
In my testing, I only saw my sessions' commands. Are you saying there's cases where the AMI will display the results of all commands?
