### ISSUE TITLE
Customizing the Node Transmit Line

### ISSUE THREAD

**Issue by wb6zsu** [AllStarLink/Allmon3#208]
**Describe the request**
 Would it be possible to add  color customization to the Node Transmit Lines (to be included in custom.css)? Most of the other sections of the webpage can be customized for color, but this one seems to be left out. At a minimum, customizing the color between "Idle" and any of the active transmit states would be nice. If the specific transmit states (Idle, Local Source, Network Source, Telemetry/Playback) could each be customized, that would be even better.

**Version Info**
1.1.1

**Comment by jxmx** [comment]
```
   /* Node Tx Local */
    --am3-node-tx-local-color: rgb(0, 0, 0);
    --am3-node-tx-local-bg-color: rgb(245, 198, 203);

    /* NOde Tx Network */
    --am3-node-tx-network-color: rgb(0, 0, 0);
    --am3-node-tx-network-bg-color: rgb(245, 198, 203);

    /* Node Tx Telem */
    --am3-node-tx-telemetry-color: rgb(0, 0, 0);
    --am3-node-tx-telemetry-bg-color: rgb(245, 198, 203);

    /* Node Tx Remote */
    --am3-node-tx-playback-remote-color: rgb(0, 0, 0);
    --am3-node-tx-playback-remote-bg-color: rgb(245, 198, 203);

    /* Node No Tx */
    --am3-node-no-tx-color: rgb(0, 0, 0);
    --am3-node-no-tx-bg-color: rgb(195, 230, 203);
```

**Comment by wb6zsu** [comment]
Thanks Jason.  Looks good!

73,
Greg
WB6ZSU
