### ISSUE TITLE
Hamvoip

### ISSUE THREAD

**Issue by darinng7o** [AllStarLink/Allmon3#213]
Will Allmon3 install & work on Hamvoip?

**Comment by jxmx** [comment]
@darinng7o  - It will not work on Hamvoip. That platform is too old with a very old version of Python3.

**Comment by jxmx** [comment]
@darinng7o Although, to be clear, you can run Allmon3 on a modern Linux distro like Debian 12 and poll the data from a Hamvoip system as long as the system with Allmon3 can get to port 5038 on the Hamvoip system. That's just using the standard Asterisk AMI interface. I do that in certain cases until I can replace all the legacy Hamvoip stuff we have.
