### ISSUE TITLE
SEVERE: Could not contact the allmon3 manager. Check the allmon3 service, webserver config, and reload the window.

### ISSUE THREAD

**Issue by omaudio** [AllStarLink/Allmon3#214]
**Describe the bug**
SEVERE: Could not contact the allmon3 manager. Check the allmon3 service, webserver config, and reload the window.

**To Reproduce**
did proper install- might be cfg issue

**Expected behavior**

**Screenshots**

**URL of Site**
If available publicly, the URL to observe the problem if it's related to the web interface

**Log Information**
Copy in any error or info logs information from /var/log/daemon.org, /var/log/syslog, or /var/log/messages depending on the Linux platform.

**Version Info**
If this is a web issue, list the "Version" or "Build ID" from the main page (on the left under the menu). If this is a backend issue, list the version of the application from the --verson command (e.g. `asl-statmon --version`) 

**Additional context**

;
; This is the master configuration file for all ASL/Asterisks node-related
; information. It is used for all server daemon processes
; (e.g. asl-statmon, asl-cmdlink) and the web interface/API.
;
; Each configuration item below is marked (R) or (O) for required or optional
; repsectively along with usage notes. The value in the table below is the
; default value for optiional items or examples for required items.
;
;[48654]
host = 127.0.0.1     # (R) DNS name or IP address of the Asterisk/ASL node
;
port = 5038          # (O) port of the Asterisk manager
;
user = admin         # (R) username of the Asterisk monitor, most 
;                      #     commonly 'admin'
;
pass = ********      # (R) password of the monitor user
; 
; multinodes =		 # (O) this node is a server hosting multiple nodes
;                      #     and this is the "primary" record for the host.
; 
; voters = n[,n,...]   # (O) List voters on this server, comma
;                      #     separate. No value disabled voters
;
pollinterval = 1     # (O) polling interval to asterisk in seconds 
;                      #     default is 1. this value can be expressed as
;                      #     a decimal fraction of a second - e.g., .5
;                      #     is 500ms, .375 is 375ms, etc.
;
vpollinterval = 1    # (O) broadcast interval of voter data in seconds
;                      #      default is 1. this value can be expressed as
;                      #      a decimal fraction of a second - e.g., .5
;                      #      is 500ms, .375 is 375ms, etc.
;
retryinterval = 15   # (O) seconds between retries if initial connection to
;                      #     asterisk is lost (optional, default 15)
;
retrycount =         # (O) number of times to retry a lost asterisk
;                      #     connection before ending (default infinite)

; For a basic installation, you chould be able to uncomment the below,
; change 1999 to your node number and set the pass= as
; set in asterisk/manager.conf
[48654]
host=127.0.0.1
user=admin
pass=********

**Comment by jxmx** [comment]
@omaudio can you please provide the requested debugging info under the **Log Information**? This ticket has insufficient information for me to provide troubleshooting.

**Comment by jxmx** [comment]
Oh are you KK6QMS from Community? Will you please attach the output of `journalctl --no-pager -u allmon3.service` to this issue please?

**Comment by omaudio** [comment]
Hi yes I am KK6QMS- 

root@Pi-ASL-48654:/home/repeater# journalctl --no-pager -u allmon3.service
-- Logs begin at Tue 2024-03-05 02:00:18 PST, end at Mon 2024-03-11 16:52:27 PDT. --
Mar 05 02:00:28 Pi-ASL-48654 systemd[1]: Starting Allmon3 daemon...
Mar 05 02:00:28 Pi-ASL-48654 systemd[1]: Started Allmon3 daemon.
Mar 05 02:00:37 Pi-ASL-48654 allmon3[615]: Traceback (most recent call last):
Mar 05 02:00:37 Pi-ASL-48654 allmon3[615]:   File "/usr/bin/allmon3", line 231, in <module>
Mar 05 02:00:37 Pi-ASL-48654 allmon3[615]:     raise e
Mar 05 02:00:37 Pi-ASL-48654 allmon3[615]:   File "/usr/bin/allmon3", line 189, in <module>
Mar 05 02:00:37 Pi-ASL-48654 allmon3[615]:     node_configuration = node_configs.NodeConfigs(config_file, filter_list)
Mar 05 02:00:37 Pi-ASL-48654 allmon3[615]:   File "/usr/lib/python3/dist-packages/asl_allmon/node_configs/__init__.py", line 21, in __init__
Mar 05 02:00:37 Pi-ASL-48654 allmon3[615]:     config_full.read(config_file)
Mar 05 02:00:37 Pi-ASL-48654 allmon3[615]:   File "/usr/lib/python3.7/configparser.py", line 696, in read
Mar 05 02:00:37 Pi-ASL-48654 allmon3[615]:     self._read(fp, filename)
Mar 05 02:00:37 Pi-ASL-48654 allmon3[615]:   File "/usr/lib/python3.7/configparser.py", line 1079, in _read
Mar 05 02:00:37 Pi-ASL-48654 allmon3[615]:     raise MissingSectionHeaderError(fpname, lineno, line)
Mar 05 02:00:37 Pi-ASL-48654 allmon3[615]: configparser.MissingSectionHeaderError: File contains no section headers.
Mar 05 02:00:37 Pi-ASL-48654 allmon3[615]: file: '/etc/allmon3/allmon3.ini', line: 11
Mar 05 02:00:37 Pi-ASL-48654 allmon3[615]: 'host = 127.0.0.1     # (R) DNS name or IP address of the Asterisk/ASL node\n'
Mar 05 02:00:37 Pi-ASL-48654 systemd[1]: allmon3.service: Main process exited, code=exited, status=1/FAILURE
Mar 05 02:00:37 Pi-ASL-48654 systemd[1]: allmon3.service: Failed with result 'exit-code'.
Mar 05 02:10:32 Pi-ASL-48654 systemd[1]: Starting Allmon3 daemon...
Mar 05 02:10:32 Pi-ASL-48654 systemd[1]: Started Allmon3 daemon.
Mar 05 02:10:34 Pi-ASL-48654 allmon3[3472]: Traceback (most recent call last):
Mar 05 02:10:34 Pi-ASL-48654 allmon3[3472]:   File "/usr/bin/allmon3", line 231, in <module>
Mar 05 02:10:34 Pi-ASL-48654 allmon3[3472]:     raise e
Mar 05 02:10:34 Pi-ASL-48654 allmon3[3472]:   File "/usr/bin/allmon3", line 189, in <module>
Mar 05 02:10:34 Pi-ASL-48654 allmon3[3472]:     node_configuration = node_configs.NodeConfigs(config_file, filter_list)
Mar 05 02:10:34 Pi-ASL-48654 allmon3[3472]:   File "/usr/lib/python3/dist-packages/asl_allmon/node_configs/__init__.py", line 21, in __init__
Mar 05 02:10:34 Pi-ASL-48654 allmon3[3472]:     config_full.read(config_file)
Mar 05 02:10:34 Pi-ASL-48654 allmon3[3472]:   File "/usr/lib/python3.7/configparser.py", line 696, in read
Mar 05 02:10:34 Pi-ASL-48654 allmon3[3472]:     self._read(fp, filename)
Mar 05 02:10:34 Pi-ASL-48654 allmon3[3472]:   File "/usr/lib/python3.7/configparser.py", line 1079, in _read
Mar 05 02:10:34 Pi-ASL-48654 allmon3[3472]:     raise MissingSectionHeaderError(fpname, lineno, line)
Mar 05 02:10:34 Pi-ASL-48654 allmon3[3472]: configparser.MissingSectionHeaderError: File contains no section headers.
Mar 05 02:10:34 Pi-ASL-48654 allmon3[3472]: file: '/etc/allmon3/allmon3.ini', line: 11
Mar 05 02:10:34 Pi-ASL-48654 allmon3[3472]: 'host = 127.0.0.1     # (R) DNS name or IP address of the Asterisk/ASL node\n'
Mar 05 02:10:34 Pi-ASL-48654 systemd[1]: allmon3.service: Main process exited, code=exited, status=1/FAILURE
Mar 05 02:10:34 Pi-ASL-48654 systemd[1]: allmon3.service: Failed with result 'exit-code'.
Mar 05 13:02:42 Pi-ASL-48654 systemd[1]: Starting Allmon3 daemon...
Mar 05 13:02:42 Pi-ASL-48654 systemd[1]: Started Allmon3 daemon.
Mar 05 13:02:44 Pi-ASL-48654 allmon3[29704]: Traceback (most recent call last):
Mar 05 13:02:44 Pi-ASL-48654 allmon3[29704]:   File "/usr/bin/allmon3", line 231, in <module>
Mar 05 13:02:44 Pi-ASL-48654 allmon3[29704]:     raise e
Mar 05 13:02:44 Pi-ASL-48654 allmon3[29704]:   File "/usr/bin/allmon3", line 189, in <module>
Mar 05 13:02:44 Pi-ASL-48654 allmon3[29704]:     node_configuration = node_configs.NodeConfigs(config_file, filter_list)
Mar 05 13:02:44 Pi-ASL-48654 allmon3[29704]:   File "/usr/lib/python3/dist-packages/asl_allmon/node_configs/__init__.py", line 21, in __init__
Mar 05 13:02:44 Pi-ASL-48654 allmon3[29704]:     config_full.read(config_file)
Mar 05 13:02:44 Pi-ASL-48654 allmon3[29704]:   File "/usr/lib/python3.7/configparser.py", line 696, in read
Mar 05 13:02:44 Pi-ASL-48654 allmon3[29704]:     self._read(fp, filename)
Mar 05 13:02:44 Pi-ASL-48654 allmon3[29704]:   File "/usr/lib/python3.7/configparser.py", line 1079, in _read
Mar 05 13:02:44 Pi-ASL-48654 allmon3[29704]:     raise MissingSectionHeaderError(fpname, lineno, line)
Mar 05 13:02:44 Pi-ASL-48654 allmon3[29704]: configparser.MissingSectionHeaderError: File contains no section headers.
Mar 05 13:02:44 Pi-ASL-48654 allmon3[29704]: file: '/etc/allmon3/allmon3.ini', line: 11
Mar 05 13:02:44 Pi-ASL-48654 allmon3[29704]: 'host = 127.0.0.1     # (R) DNS name or IP address of the Asterisk/ASL node\n'
Mar 05 13:02:44 Pi-ASL-48654 systemd[1]: allmon3.service: Main process exited, code=exited, status=1/FAILURE
Mar 05 13:02:44 Pi-ASL-48654 systemd[1]: allmon3.service: Failed with result 'exit-code'.
Mar 06 17:02:03 Pi-ASL-48654 systemd[1]: Starting Allmon3 daemon...
Mar 06 17:02:03 Pi-ASL-48654 systemd[1]: Started Allmon3 daemon.
Mar 06 17:02:05 Pi-ASL-48654 allmon3[26050]: Traceback (most recent call last):
Mar 06 17:02:05 Pi-ASL-48654 allmon3[26050]:   File "/usr/bin/allmon3", line 231, in <module>
Mar 06 17:02:05 Pi-ASL-48654 allmon3[26050]:     raise e
Mar 06 17:02:05 Pi-ASL-48654 allmon3[26050]:   File "/usr/bin/allmon3", line 189, in <module>
Mar 06 17:02:05 Pi-ASL-48654 allmon3[26050]:     node_configuration = node_configs.NodeConfigs(config_file, filter_list)
Mar 06 17:02:05 Pi-ASL-48654 allmon3[26050]:   File "/usr/lib/python3/dist-packages/asl_allmon/node_configs/__init__.py", line 21, in __init__
Mar 06 17:02:05 Pi-ASL-48654 allmon3[26050]:     config_full.read(config_file)
Mar 06 17:02:05 Pi-ASL-48654 allmon3[26050]:   File "/usr/lib/python3.7/configparser.py", line 696, in read
Mar 06 17:02:05 Pi-ASL-48654 allmon3[26050]:     self._read(fp, filename)
Mar 06 17:02:05 Pi-ASL-48654 allmon3[26050]:   File "/usr/lib/python3.7/configparser.py", line 1079, in _read
Mar 06 17:02:05 Pi-ASL-48654 allmon3[26050]:     raise MissingSectionHeaderError(fpname, lineno, line)
Mar 06 17:02:05 Pi-ASL-48654 allmon3[26050]: configparser.MissingSectionHeaderError: File contains no section headers.
Mar 06 17:02:05 Pi-ASL-48654 allmon3[26050]: file: '/etc/allmon3/allmon3.ini', line: 11
Mar 06 17:02:05 Pi-ASL-48654 allmon3[26050]: 'host = 127.0.0.1     # (R) DNS name or IP address of the Asterisk/ASL node\n'
Mar 06 17:02:05 Pi-ASL-48654 systemd[1]: allmon3.service: Main process exited, code=exited, status=1/FAILURE
Mar 06 17:02:05 Pi-ASL-48654 systemd[1]: allmon3.service: Failed with result 'exit-code'.
Mar 06 17:03:23 Pi-ASL-48654 systemd[1]: Starting Allmon3 daemon...
Mar 06 17:03:23 Pi-ASL-48654 systemd[1]: Started Allmon3 daemon.
Mar 06 17:03:24 Pi-ASL-48654 allmon3[26408]: Traceback (most recent call last):
Mar 06 17:03:24 Pi-ASL-48654 allmon3[26408]:   File "/usr/bin/allmon3", line 231, in <module>
Mar 06 17:03:24 Pi-ASL-48654 allmon3[26408]:     raise e
Mar 06 17:03:24 Pi-ASL-48654 allmon3[26408]:   File "/usr/bin/allmon3", line 189, in <module>
Mar 06 17:03:24 Pi-ASL-48654 allmon3[26408]:     node_configuration = node_configs.NodeConfigs(config_file, filter_list)
Mar 06 17:03:24 Pi-ASL-48654 allmon3[26408]:   File "/usr/lib/python3/dist-packages/asl_allmon/node_configs/__init__.py", line 21, in __init__
Mar 06 17:03:24 Pi-ASL-48654 allmon3[26408]:     config_full.read(config_file)
Mar 06 17:03:24 Pi-ASL-48654 allmon3[26408]:   File "/usr/lib/python3.7/configparser.py", line 696, in read
Mar 06 17:03:24 Pi-ASL-48654 allmon3[26408]:     self._read(fp, filename)
Mar 06 17:03:24 Pi-ASL-48654 allmon3[26408]:   File "/usr/lib/python3.7/configparser.py", line 1079, in _read
Mar 06 17:03:24 Pi-ASL-48654 allmon3[26408]:     raise MissingSectionHeaderError(fpname, lineno, line)
Mar 06 17:03:24 Pi-ASL-48654 allmon3[26408]: configparser.MissingSectionHeaderError: File contains no section headers.
Mar 06 17:03:24 Pi-ASL-48654 allmon3[26408]: file: '/etc/allmon3/allmon3.ini', line: 11
Mar 06 17:03:24 Pi-ASL-48654 allmon3[26408]: 'host = 127.0.0.1     # (R) DNS name or IP address of the Asterisk/ASL node\n'
Mar 06 17:03:24 Pi-ASL-48654 systemd[1]: allmon3.service: Main process exited, code=exited, status=1/FAILURE
Mar 06 17:03:24 Pi-ASL-48654 systemd[1]: allmon3.service: Failed with result 'exit-code'.
root@Pi-ASL-48654:/home/repeater#

**Comment by jxmx** [comment]
Okay, I thought this was a copy/paste artifact but it looks like you uncommented the directions part of `allmon3.ini`. Make sure that everything before  those last 4 lines either starts with a `;` or a completely empty line. Realistically you should have a file that has ONLY:

```
[48654]
host=127.0.0.1
user=admin
pass=********
```

Everything else should be comments or empty lines.

**Comment by omaudio** [comment]
Ok now it works. I was really unclear reading the instructions just did not make sense to me. Thx for the help.
