### ISSUE TITLE
Disconnect option in node rows

### ISSUE THREAD

**Issue by dandrzejewski** [AllStarLink/Allmon3#215]
**Describe the request**
I would like to be able to easily disconnect a node by clicking an icon or button in the row in which the node is listed.  This would be much easier than copying the node number, clicking the link button, selecting disconnect from the dropdown, and pasting the node number in, and then clicking execute.

Perhaps other contextual options could be added there as well.

**Version Info**
1.2.0

**Comment by jxmx** [comment]
@dandrzejewski If if you click on the row that you want to disconnect before clicking on the link icon, it will prefill that node into the modal box when it pops up.

**Comment by jxmx** [comment]
This will appear in v1.3

**Comment by tsawyer** [comment]
We have this feature now, altho it is somewhat hidden. If you click the node number in any row and then open the link dialog, the node number is filled in.

**Comment by jxmx** [comment]
This commit adds a “shortcut” button to the link table when a user is logged in. Makes the option more obvious.

**Comment by tsawyer** [comment]
Interface clutter is a concern. A button on every row sounds like a mess. But I haven't seen it.  Leaving it up to your judgement.
