### ISSUE TITLE
WS_BIND_ADDR should probably be 127.0.0.1 by default

### ISSUE THREAD

**Issue by charlieh0tel** [AllStarLink/Allmon3#216]
**Describe the bug**
allmon listens on all interfaces by default.  this is probably not the right default setting.   these ports should not be available to inside and out networks by default.

**To Reproduce**
1. install normally.
2. observe open tcp ports with ss or netstat

**Expected behavior**
allow ports only on loopback.

i.e. WS_BIND_ADDR should probably be 127.0.0.1 out of the box.

**Version Info**

at HEAD (ea1ccd938980d852eab783335ca7888221e29612)

**Comment by jxmx** [comment]
Not a bug. This was a design choice. The allmon3 daemon was designed to be completely uncoupled from the web front end. Listening only on 127.0.0.1 defeats the purpose and is IPv6 unfriendly. I will think about this.

**Comment by charlieh0tel** [comment]
np.  that's right.  should also listen on ipv6 local address.

the issue is whether these sockets are exposed to other networks.

**Comment by jxmx** [comment]
After thinking a lot about this, I'm going to leave this as-is. It's not running as root and the risk profile is low.
