### ISSUE TITLE
Minimize need to edit allmon3.ini

### ISSUE THREAD

**Issue by Allan-N** [AllStarLink/Allmon3#217]
**Describe the request**
Why do I need to edit "allmon3.ini" when the same information is already present on my system?  Have you thought about having Allmon3 pull needed information from "rpt.conf", "manager.conf", etc?  If you did that then we wouldn't have to worry (nor track down issues) when the configurations get out-of-sync.

And, yes, I'm thinking mostly about local nodes.

**Comment by jxmx** [comment]
I suppose maybe the right thing would be a `postinst` script that parses out the right files on install and, if it's configured, use that instead of the "1999" config. That's probably a good idea.

**Comment by Allan-N** [comment]
Using a `postinst` script would only help @ install.  Having Allmon3 parse the files @ startup would handle added nodes, changed node #'s, removed nodes, AMI pw changes, etc.

**Comment by jxmx** [comment]
I don't think what's described here is the way to go. What we likely need is functionality in Pi Appliance that, for fully-controlled installs, we rebuild the configuration on the fly.
