### ISSUE TITLE
Show the TX Time on the actively TXing Node

### ISSUE THREAD

**Issue by JBM1866** [AllStarLink/Allmon3#218]
**Describe the request**
The current TX Node goes to the top of the list and is shown in green.
There is no TX timer displayed on the interface - showing how long the node has been transmitting for continuously.
Is this a setting that can be enabled?

**Version Info**
Allmon v3
1.2.0

**Comment by jxmx** [comment]
Asterisk/app_rpt does not track this by default so there's no setting to enable it. It's something I could consider for a future release to track how long the current transmission is. I likely wouldn't try to track TX times by node.

**Comment by JBM1866** [comment]
Hi Jason,
That would be perfect if it could just show the tx time in the top bar where is stays that it’s transmitting and count up from the last status change.

It’s a very handy feature for managing a hub and also for net controllers.

Thanks for your work on allmon3, it looks and works great!! :)

**Comment by jxmx** [comment]
Will appear in v1.3
