### ISSUE TITLE
TLB Connections have unique xnode format

### ISSUE THREAD

**Issue by k6ian** [AllStarLink/Allmon3#219]
Please look into properly showing tlb private nodes. As you can see in the screenshot below, private node 1100 is a tlb connection and it doesn't properly show in either its own line, nor when it is connected to the hub.

![image](https://github.com/AllStarLink/Allmon3/assets/71847111/ff5e5bbc-87dc-4894-bf27-c04cb1449570)

**Version Info**
Currently running Allmon v3 1.2.0

**Comment by jxmx** [comment]
@k6ian - Can you send me the output of `rpt xnode 525250` and `rpt stats 525250` when one of these chan_tlb devices is connected? I've never encountered someone using it before. I'll have to see if it's possible to differentiate between these and Echolink nodes.

**Comment by k6ian** [comment]
Cmd: rpt xnode 525250

![image](https://github.com/AllStarLink/Allmon3/assets/71847111/3c2e06a3-eac8-406b-8b02-b57e47db0c24)

Second half:

![image](https://github.com/AllStarLink/Allmon3/assets/71847111/dd9933b1-192d-426a-9416-c427aae3588e)


Cmd: rpt stats 525250

![image](https://github.com/AllStarLink/Allmon3/assets/71847111/2a94479d-9381-4889-9a80-451d91083bed)

Threw in Cmd rpt xnode 1100

![image](https://github.com/AllStarLink/Allmon3/assets/71847111/2eb19220-59c5-4487-bbcc-7d52939a6265)

**Comment by wd5m** [comment]
I think you will find the connected tlb node simply shows up as a private
node number. I work around this issue on Supermon by creating a
privatenodes.txt file which is combined with astdb.txt by astdb.php.

David McAnally
WD5M

**Comment by k6ian** [comment]
Yeah, I did add it to Allmon3 like a private node. It does show up.
It’s just getting the “Last Recv”, “Conn Time”, “Direction”, and “Connect State” to register in the correct boxes.

Just wondering if there is a way on the back end to recognize that it is a “tlb” node and put the stuff in the right places.

Thanks,
Ian – K6IAN

**Comment by wd5m** [comment]
Yeah, I think that requires a variation on parsing the results from the
Allstar manager service for tlb/private nodes, or EchoLink, versus Allstar
nodes. It's been a while since I looked at those details. I might be
mistaken about that.

David WD5M

**Comment by jxmx** [comment]
There's no column separators in the data so every unique variant is a fun text processing problem. Can you please supply the output requested as text files so I can inspect the byte contents?

**Comment by wd5m** [comment]
Not sure this will help with Allmon3, but a while back I added this
modification to my copy of Supermon server.php for parsing EchoLink nodes.
I believe adding " || count($arr) < 6" to the if statement patched the
parsing issue with tlb private nodes. It would be great if Allstar returned
JSON or something formatted that we can parse reliably. :-)

    // Parse 'rptStat Conn:' lines.
    $lines = explode("\n", $rptStatus);
    foreach ($lines as $line) {
        if (preg_match('/Conn: (.*)/', $line, $matches)) {
            $arr = preg_split("/\s+/", trim($matches[1]));
            if((is_numeric($arr[0]) && $arr[0] > 3000000) || count($arr) <
6) { // WD5M 09/2022
                // no ip when echolink
                $conns[] = array($arr[0], "", $arr[1], $arr[2], $arr[3],
$arr[4]);
            } else {
                $conns[] = $arr;
            }
        }
(...)



David McAnally
WD5M

**Comment by k6ian** [comment]
[rpt-xnode-525250.txt](https://github.com/AllStarLink/Allmon3/files/15470518/rpt-xnode-525250.txt)

**Comment by k6ian** [comment]
[rpt-xnode-525250-tlb-not-connected.txt](https://github.com/AllStarLink/Allmon3/files/15470664/rpt-xnode-525250-tlb-not-connected.txt)

**Comment by k6ian** [comment]
Weirdness... If I connect HUB node to private tlb node it doesn't display right. See this picture..
![image](https://github.com/AllStarLink/Allmon3/assets/71847111/e4b6c129-24f8-4a2f-983e-d7839ddeace2)

If I connect private tlb node out to the HUB node, it displays correctly.
![image](https://github.com/AllStarLink/Allmon3/assets/71847111/d8d3ecb6-9147-4e2a-8912-40f2684f6382)

[rpt-xnode-525250-tlb-connected-via-1100-out.txt](https://github.com/AllStarLink/Allmon3/files/15470809/rpt-xnode-525250-tlb-connected-via-1100-out.txt)

**Comment by k6ian** [comment]
Nevermind, I can't link it that way. It doesn't connect to the tlb server.
![image](https://github.com/AllStarLink/Allmon3/assets/71847111/c88d62fd-4a97-4846-8a7d-05462de0c336)

If I issue the command from the HUB node to connect to the tlb private node, it connects.
![image](https://github.com/AllStarLink/Allmon3/assets/71847111/4bd89ee9-c919-4a94-8ccc-66c7605e1517)

**Comment by k6ian** [comment]
Is any more info needed to be able to troubleshoot this?

Here is a screenshot on ASL3 with Allmon3 running:
![image](https://github.com/user-attachments/assets/a02f35b3-a675-4eb8-84d2-2d0642017777)

**Comment by jxmx** [comment]
Can you send me the output (in text) of `xstat 525240`.

**Comment by jxmx** [comment]
https://github.com/AllStarLink/Allmon3/issues/254

**Comment by jxmx** [comment]
@k6ian - Will you please try copying https://github.com/AllStarLink/Allmon3/blob/xstat_rewrite/src/asl_allmon/ami_parser/__init__.py to `/usr/lib/python3/dist-packages/asl_allmon/ami_parser/__init__.py`. See if this resolves the issue.

**Comment by k6ian** [comment]
Hi Jason,

I copied the original file to .bak file, then put the new file in. I then issued a systemctl restart allmon3 and now I’m not getting anything. Attached is both files, the original as .bak and the new one.

***@***.***

***@***.***

**Comment by jxmx** [comment]
I just pushed a bunch of additional changes. Please try them.

**Comment by k6ian** [comment]
Fixed! Node 1100 is the TLB Connection.

![image](https://github.com/user-attachments/assets/b369cb61-de90-4c15-85a4-3e4257f5a1ac)

**Comment by jxmx** [comment]
Excellent!
