### ISSUE TITLE
Whitelist / Blacklist feature enhancement for Allmon3

### ISSUE THREAD

**Issue by k6ian** [AllStarLink/Allmon3#220]
Please look to incorporate the AllStarLink node Whitelist / Blacklist feature into Allmon3, to make it easier for adding and removing nodes right from Allmon3 instead of having to log into cmd line.

For reference, here is the link to AllStarLink Whitelist / Blacklist explanation: [https://wiki.allstarlink.org/wiki/Blacklist_or_whitelist](https://wiki.allstarlink.org/wiki/Blacklist_or_whitelist)

**Comment by jxmx** [comment]
Note: feature will only be supported on modern Asterisk/app_rpt

**Comment by jxmx** [comment]
```
database put whitelist/1999 2000 "whitelist node 2000 for node 1999"
database put blacklist/1998 2000 "blacklist node 2000 for node 1998"
```

**Comment by jxmx** [comment]
Will appear in 1.3.0
