### ISSUE TITLE
Number of nodes connected

### ISSUE THREAD

**Issue by vk3xem** [AllStarLink/Allmon3#221]
Would it be possible to add a counter that indicates the number of nodes connected to the Allmon dashboard.

This feature is on Supermon and whilst only cosmetic and trivial, it would still be able to see the number of nodes connected at a glance.

73 de Simon, VK3XEM.

**Comment by tsawyer** [comment]
Assuming you want to see a count of all linked nodes, Allmon3 could get that from `rpt xnodes 1999` from the `RPT_NUMLINKS=16` value.

Is that what you're after?

**Comment by vk3xem** [comment]
Yes that is what I am looking for.  Have no idea how it would be implemented though being an end user.

**Comment by jxmx** [comment]
It's trivial enough to add to the dashboard display

**Comment by vk3xem** [comment]
Tank you.

**Comment by jxmx** [comment]
Will appear in v1.3

**Comment by vk3xem** [comment]
That is awesome guys, done in a matter of hours.  Look forward to seeing in v1.3

Thank you.
