### ISSUE TITLE
Can Allmon3 configurable to be accessed outside of the internal network?

### ISSUE THREAD

**Issue by KD5FMU** [AllStarLink/Allmon3#225]
**Describe the request**
I would like the ability to change the bind web port of Allmon3 to a specific non-standard web port, so that I can port forward for outside of local network requests to access the Allmon3 in the field. My ISP will not open port 80.

**Version Info**
V.1.2.1

**Comment by jxmx** [comment]
@KD5FMU - This isn't an Allmon3 feature per-se, it's entirely controlled by the webserver you're running. Assuming it's Apache2 on Debian, you can edit `/etc/apache2/ports.conf` and change the ports to whatever works for your ISP. Alternatively, if you're behind a NAT device/router/etc, port forward in something like 8080 externally to port 80 on the device running your Allmon3/ASL host.

**Comment by KD5FMU** [comment]
Yes I have been doing that to no avail. I have done the same thing on other installs running apache2 and it worked. Just not for this one. Not sure Why.

**Comment by tsawyer** [comment]
If there is a firewall on your system changing the port won't work. Try port forwarding 8080 to 80 and 8443 to 443.

**Comment by jxmx** [comment]
do you have any errors or example we can see?

**Comment by KD5FMU** [comment]
![Port8080-allmon3](https://github.com/AllStarLink/Allmon3/assets/138044297/20bdc694-1e9e-48d8-88e5-01f075e5e37f)
![Port8443-allmon3](https://github.com/AllStarLink/Allmon3/assets/138044297/88bab514-5ed1-40c9-86da-6f311dd238be)
![Port8443](https://github.com/AllStarLink/Allmon3/assets/138044297/a99a9edc-5dca-4fbb-b482-82d9cdfac01a)
![Port8080](https://github.com/AllStarLink/Allmon3/assets/138044297/df4d6125-3b75-4915-83b5-8106de613677)

**Comment by jxmx** [comment]
For the 8443 port listener, everything works fine for me if I go to https://47.217.204.249:8443/. Note the error is telling you that you're trying to use http:// when you should be using https:// for port 8443. 

Regarding port 8080, that port is not open to the Internet. Your router or something upstream of you is sending a TCP Reset as soon as the connection starts to block inbound to that port.

![image](https://github.com/AllStarLink/Allmon3/assets/21324335/7fae693e-6b4a-471f-8ba3-719612082bc6

**Comment by jxmx** [comment]
```
jdm@calcium:~ $ telnet 47.217.204.249 8080
Trying 47.217.204.249...
telnet: Unable to connect to remote host: Connection refused
jdm@calcium:~ $
```
``` $ sudo tcpdump -nn -vv -- host 47.217.204.249
tcpdump: listening on enp1s0, link-type EN10MB (Ethernet), snapshot length 262144 bytes

12:45:52.115806 IP (tos 0x0, ttl 64, id 47710, offset 0, flags [DF], proto TCP (6), length 60)
    172.17.16.40.47006 > 47.217.204.249.8080: Flags [S], cksum 0xb93a (incorrect -> 0x22f5), seq 3275699222, win 64240, options [mss 1460,sackOK,TS val 2772630854 ecr 0,nop,wscale 7], length 0
12:45:52.179534 IP (tos 0x0, ttl 48, id 0, offset 0, flags [DF], proto TCP (6), length 40)
    47.217.204.249.8080 > 172.17.16.40.47006: Flags [R.], cksum 0x283f (correct), seq 0, ack 3275699223, win 0, length 0
```
That second line `Flags [R.]`  is a firewall-generated TCP reset to block the connection.

**Comment by KD5FMU** [comment]
I was able to open also with the https on port 8443 but I changed 8080 out 80 in to 555 out and 80 in and still no working. But since the 8443 works I don’t need the other. Do I?Fred McGuire, ***@***.*** Jun 18, 2024, at 11:53 AM, Jason McCormick ***@***.***> wrote:﻿
Reopened #225.

**Comment by jxmx** [comment]
I believe this is resolved. Please reopen if not.
