### ISSUE TITLE
Bind Address Issue

### ISSUE THREAD

**Issue by ShaYmez** [AllStarLink/Allmon3#226]
There is some sort of binding issue from fresh install deb 12, ASL 3. Installed Allmon3 from apt. Unable to connect to any nodes inside or outside, debug report below

INFO: (allmon3) starting allmon3 master ws on port 16080
INFO: (allmon3) starting node_db updater
DEBUG: (asl_allmon.node_db) entering full_update
DEBUG: (asl_allmon.node_db) entering get_allmon_db()
INFO: (asl_allmon.node_db) Retrieving database from https://allmondb.allstarlink.org/
INFO: (asl_allmon.node_db) Updated node database in 1.04 seconds
DEBUG: (asl_allmon.node_db) exiting getAllMonDB()
INFO: (asl_allmon.node_db) populated AllStarlink database
^CINFO: (allmon3) exiting on signal 2
DEBUG: (allmon3) killing task: Task-2
DEBUG: (allmon3) killing task: Task-3
INFO: (allmon3) all tasks in start_tasks() cancelled
DEBUG: (allmon3) finally of start_tasks()
DEBUG: (allmon3) __main__ finally
root@ASL-GB3NM:/etc/allmon3# systemctl restart allmon3
root@ASL-GB3NM:/etc/allmon3# allmon3 --debug
DEBUG: (allmon3) config file is /etc/allmon3/allmon3.ini
DEBUG: (allmon3) web config file is /etc/allmon3/web.ini
INFO: (asl_allmon.web_configs) Allmon3 Master HTTP port is 16080
INFO: (asl_allmon.web_configs) Allmon3 websockets starting port is 16700
INFO: (asl_allmon.web_configs) Binding sevices to all addresses
INFO: (allmon3) no %s found; no menu data available
DEBUG: (allmon3) user_table file is /etc/allmon3/users
DEBUG: (allmon3) restriction_table file is /etc/allmon3/user-restrictions
DEBUG: (asl_allmon.security) loaded 2 entries from /etc/allmon3/users
DEBUG: (asl_allmon.security) loaded 0 entries from /etc/allmon3/user-restrictions
DEBUG: (allmon3) starting the main work loop
DEBUG: (allmon3) enter start_tasks()
INFO: (allmon3) starting allmon3 master ws on port 16080
INFO: (allmon3) starting node_db updater
DEBUG: (asl_allmon.node_db) entering full_update
DEBUG: (asl_allmon.node_db) entering get_allmon_db()
INFO: (asl_allmon.node_db) Retrieving database from https://allmondb.allstarlink.org/
DEBUG: (allmon3) exception of start_tasks()
DEBUG: (allmon3) finally of start_tasks()
DEBUG: (allmon3) __main__ finally
Traceback (most recent call last):
  File "/usr/bin/allmon3", line 236, in <module>
    asyncio.run(start_tasks())
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/bin/allmon3", line 120, in start_tasks
    raise e
  File "/usr/bin/allmon3", line 107, in start_tasks
    await asyncio.gather(*tasks)
  File "/usr/lib/python3/dist-packages/asl_allmon/allmon3_server/__init__.py", line 291, in main
    await site.start()
  File "/usr/lib/python3/dist-packages/aiohttp/web_runner.py", line 121, in start
    self._server = await loop.create_server(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 1525, in create_server
    raise OSError(err.errno, 'error while attempting '
OSError: [Errno 98] error while attempting to bind on address ('0.0.0.0', 16080): address already in use
root@ASL-GB3NM:/etc/allmon3# ss -ltnp
State       Recv-Q      Send-Q           Local Address:Port            Peer Address:Port      Process                                 
LISTEN      0           128                    0.0.0.0:16080                0.0.0.0:*          users:(("allmon3",pid=3795,fd=8))      
LISTEN      0           128                    0.0.0.0:22                   0.0.0.0:*          users:(("sshd",pid=441,fd=3))          
LISTEN      0           10               192.168.1.196:5040                 0.0.0.0:*          users:(("asterisk",pid=391,fd=7))      
LISTEN      0           128                       [::]:16080                   [::]:*          users:(("allmon3",pid=3795,fd=7))      
LISTEN      0           128                       [::]:22                      [::]:*          users:(("sshd",pid=441,fd=4))          
LISTEN      0           511                          *:80                         *:*          users:(("apache2",pid=459,fd=4),("apache2",pid=458,fd=4),("apache2",pid=457,fd=4))

Produces same result with or without allmon3.ini configured. This is out the box. Fresh install deb 12. The port is not used anywhere else other than itself allmon3.

M0VUB

**Comment by jxmx** [comment]
Your SS output looks like there is already one Allmon3 running?

**Comment by ShaYmez** [comment]
ahh yes, good spot, thats because im running --debug plus system unit. Just trying to figue out why local nodes arent connecting. Thanks Jason ;)

**Comment by jxmx** [comment]
Ahh... You can run Allmon3 as any user... Was designed that way. Good luck and let me know if I can help further.

**Comment by ShaYmez** [comment]
Thanks Jason, great work btw ;)On 2 Jul 2024, at 01:14, Jason McCormick ***@***.***> wrote:﻿
Ahh... You can run Allmon3 as any user... Was designed that way. Good luck and let me know if I can help further.

**Comment by ShaYmez** [comment]
I’ve worked out why local nodes weren’t connecting. They were connecting local on the machine no problem… by viewing locally on port 80,  but I have a reverse proxy in place for port 80… I need to view the dash external, because it’s remote node …. So need to look at the websocket connection as well he he :) On 2 Jul 2024, at 01:39, Shane Daley ***@***.***> wrote:﻿Thanks Jason, great work btw ;)On 2 Jul 2024, at 01:14, Jason McCormick ***@***.***> wrote:﻿
Ahh... You can run Allmon3 as any user... Was designed that way. Good luck and let me know if I can help further.
