### ISSUE TITLE
allmon doesn't ignore comments in configuration file if the line doesn't begin with them.

### ISSUE THREAD

**Issue by fjb59** [AllStarLink/Allmon3#227]
in configuration file, you have some parameters alread setp but commented out
because they are commented out at the begginng of the line allmon ignores them. but it doesn't ignore embedded comments
**To Reproduce**
edit /etc/allmon3/allmon3.ini

uncomment the commented out example lines such as 
[590250]
 host = 127.0.0.1 # ip address or dns resolvable host
 port = 5038 # listening port 
 user = admin # asterisk mananger user name
 pass = badpassword # change this password

but leave the embedded comments in

**Expected behavior**
the parcel should ignore the comment tag, ';' or '#' and everything after it. It doesn't. it parses it as part of the parameter so in this case it thinks the username you are trying to log in with is 'admin # asterisk mananger user name' rather than just admin.

**Log Information**

i tracked this error by logging into asterisk via debug mode. it told me what i was trying to log in as. Also allmon3 --debug reprted that it couldn't cast  ' 5038 # listening port '

**Version Info**
Allmon v3
1.2.1

**Additional context**

removing embedded comments from the end of the lines solves the problem but
all other software i've used allows embedded comments at the end of parameters. some people like myself like to leave them in.

**Comment by jxmx** [comment]
The standard syntax of an "INI File" doesn't support inline trailing comments. The Python INI parser is behaving to-spec. I'll leave this open for now to maybe add a note in the files about the trailing comments are for illustrative purposes only.

**Comment by fjb59** [comment]
As long as people know to remove the inline comments. It should save confusion. It took me a while to track it down.

**Comment by jxmx** [comment]
This will be fixed in 1.3.0
