### ISSUE TITLE
Change the color of menu buttons Allmon3

### ISSUE THREAD

**Issue by w8cpt** [AllStarLink/Allmon3#228]
**Describe the request**
I'd like to be able to change the colors of the grey menu buttons on the left...

**Screenshots**
See attached

**Version **
Allmon3
![IMG_20240715_174454_550](https://github.com/user-attachments/assets/0df231a9-8fbc-48e7-8b68-bb107432cf48)

**Comment by Pross** [comment]
You already can with CSS, are you trying to change the colour of all of them or one of them?

`#sidebarMenu a { background-color: green}` for example
