### ISSUE TITLE
Floating Linking Command Window

### ISSUE THREAD

**Issue by wb6zsu** [AllStarLink/Allmon3#229]
**Describe the request**
If possible, please allow the Linking Command window to float to allow viewing of the main Dashboard window while making entries in the command window.

Often while trying to connect or disconnect (or other commands) I would like to be able to reference the Dashboard. The problem with the fixed command window is that it blocks portions of the Dashboard.

**Screenshots**
If applicable, add screenshots to help explain your request

**Version Info**
1.2.0

**Comment by jxmx** [comment]
Bootstrap does not support floating/relocatable modals.
