### ISSUE TITLE
Nav Menu single node has non-functional node links

### ISSUE THREAD

**Issue by eliggett** [AllStarLink/Allmon3#234]
**Describe the bug**
Upgraded just now to the latest release (1.3) running on ASL3 with a Pi. The Pi has one local node, and the allmon3 install connects to two other machines for a total of three managed nodes. Prior Allmon3 (1.2 I believe) did not exhibit this issue. 

The single-node buttons on the left-hand side, which are in my case automatically generated (I do not have a menu.ini), contain links to "#" which do not function. When clicked, nothing happens. 

**Expected**: 
Click on a node button takes you to the single-node view for that node

**What happens**:
Clicking on the node button doesn't do anything. 

**Potential fix**: 

This can be fixed by changing functions.js to include "${n}" where the navMenu is defined. Someone with more knowledge of this program should verify that this is the correct place to insert such a fix. (That is why this is not a PR.)

Current code of functions.js: 

```
let allNodes = await getAPIJSON("master/node/listall")
        for(const n of allNodes){
        navMenu = navMenu.concat(`
            <div class="btn-group">
                <a href="#" class="btn btn-secondary" role="button" onclick="changeNodeListSingle(${n})">${n}</a>
            </div>`);
        }
```

Patched code (works for me): 

```
let allNodes = await getAPIJSON("master/node/listall")
        for(const n of allNodes){
        navMenu = navMenu.concat(`
            <div class="btn-group">
                <a href="#${n}" class="btn btn-secondary" role="button" onclick="changeNodeListSingle(${n})">${n}</a>
            </div>`);
        }
```

**Comment by eliggett** [comment]
Also... I am not at all a javascript programmer, but where is ```changeNodeListSingle``` defined?

**Comment by jxmx** [comment]
Looks like a code regression here. I will look.

**Comment by jxmx** [comment]
Try upgrading to v1.3.1 now in the beta package feed.
