### ISSUE TITLE
Makefile does not set permissions for allmon3 config files

### ISSUE THREAD

**Issue by eliggett** [AllStarLink/Allmon3#238]
**Describe the bug**
Using the Makefile to build the system, some of the installed files in /etc/allmon3 cannot be read by the allmon3 process. 

**To Reproduce**
1. Build allmon3 from source
2. Start the new allmon3 service
3. Examine logs, witness that it cannot read some of the config files

**Expected behavior**
Expected: The Makefile would set the file's group ownership to "allmon3"

**Version Info**
Release Allmon3 1.3.1-2 on R Pi ASL3 

**Additional context**
With some modifications, the Makefile can run the "install" program with the ```--group=allmon3``` argument for the ```CONF_FILES```, and keep the other permissions, which are just fine, as they are. 

This will really help people doing a first-time install or an upgrade which they have not done on their own before.

**Comment by jxmx** [comment]
As noted in the README.md, installation from `make install` is not supported. The `make install` target exists specifically for packaging only. Allmon3 is intended to be installed as a package from the Apt repository or, for people who want to customize something, by hand. If you're running this on the Pi ASL3 appliance you can just use normal package updates to get the latest version.

**Comment by jxmx** [comment]
Actually I changed my mind on this. I'll fix this so it works.

**Comment by jxmx** [comment]
Fixed in Pull #239
