### ISSUE TITLE
Allowlist Entry / Denylist Entry Error

### ISSUE THREAD

**Issue by k6ian** [AllStarLink/Allmon3#240]
**Describe the bug**
Once authenticated and you select either Allowlist Entry or Denylist Entry, no option is given for specifying the node number to enter. If you click execute, it comes back “ERR: Usage: database put”.

Show and delete database commands seem to work.

**Expected behavior**
A dialog box to enter the node # to add to either database.

**Screenshots**
![IMG_0133](https://github.com/user-attachments/assets/c769be1f-a6fd-40aa-b532-70f7fab3ebaf)

**Version Info**
v 1.3.1

**Comment by jxmx** [comment]
Ugh, clearly I didn't test this closely enough and just relied on the documentation. Quick fix is edit `/etc/allmon3/web.ini` and fix these lines:

```
database put allowlist/@/% "Reason Here" = Alllowlist Entry
database put denylist/@/% "Reason Here" = Denylist Entry
```

to this

````
database put allowlist/@ % "Reason Here" = Alllowlist Entry
database put denylist/@ % "Reason Here" = Denylist Entry

```

**Comment by k6ian** [comment]
@jxmx I updated /etc/allmon3/web.ini with:

database put allowlist/@ % "Reason Here" = Alllowlist Entry
database put denylist/@ % "Reason Here" = Denylist Entry

This is what I am getting after issuing: systemctl restart allmon3 & clearing all browser cookies

![image](https://github.com/user-attachments/assets/b39c957a-82ec-49d8-85ae-06ca038cb70e)

There needs to be an actual entry box to enter in specific node # to add to either the Allowlist or Denylist.

Also, you have an extra "l" in: database put allowlist/@ % "Reason Here" = Al**l**lowlist Entry

**Comment by jxmx** [comment]
So I wasn't done testing yet. But, yes, there's more to it than that. In `/etc/allmon3/web.ini` change those lines to the following:

```
database put allowlist/@ % &quot;Reason Here&quot; = Allowlist Entry
database put denylist/@ % &quot;Reason Here&quot; = Denylist Entry
```

You'll also need the completed 1.3.2-2 code. If you click on a line before entering the command modal it will prepopulate the node number. Otherwise you have to hand-edit "NODE". Then also need to update the reason and the quotes have to stay.

**Comment by jxmx** [comment]
Okay 1.3.2 is done and you should be able to test now.
