### ISSUE TITLE
allmon3 not working correctly through cloudflare/nginx

### ISSUE THREAD

**Issue by K1WIZ** [AllStarLink/Allmon3#243]
I have the latest version of allmon3 installed at:
https://hamhub.wizworks.net/allmon3

This is behind cloudflare --> nginx reverse proxy --> debian12 ASL node

I can get the allmon3 page to load just fine, but I can't see the node on the dashboard  (node 60454).  It just renders blank except the logo and "home" button.

If I access the ASL debian box with allmon on it, http://10.0.1.165/allmon  locally over the lan, it renders fine.
if I set hamhub.wizworks.net in my /etc/hosts file to point to my nginx box, I see a little more (can actually see a 60454 button under home, and a bit more dashboard elements), but I see a message:

`
60454 - Unavailable Node
Conns: 0
Up: 0
Allmon3 is not responding to requests for this node. Check server logs.
`

Nginx reverse proxy config:

`
server {
listen 80;
server_name hamhub.wizworks.net;
rewrite ^ https://$host$request_uri permanent;
}

server {
    listen 443 ssl http2;
    server_name hamhub.wizworks.net;
    ssl_certificate /etc/nginx/certs/prox-selfsigned.crt;
    ssl_certificate_key /etc/nginx/certs/prox-selfsigned.key;
    ssl_session_cache builtin:1000 shared:SSL:10m;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers HIGH:!aNULL:!eNULL:!EXPORT:!CAMELLIA:!DES:!MD5:!PSK:!RC4;
    ssl_prefer_server_ciphers on;

    client_max_body_size 256M;

    access_log /var/log/nginx/hamhub-access.log combined if=$loggable;
    error_log /var/log/nginx/hamhub-error.log;

    location /allmon3/ {
        proxy_pass http://10.0.1.165:80;  # Adjust this to match your Allmon3 setup
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
`

It seems like allmon3 is not written to work through reverse proxies or cloudflare.   Can this be fixed?  I have this co-located with other hosts on the same network, and I really don't want to expose the dashboard on a non-standard port to the world.

**Comment by jxmx** [comment]
There is nothing inherently proxy-unfriendly about Allmon3. You just have to make sure that you're properly proxying the websockets as websockets vs. everything else. In your snippet above, it looks like (without testing) you're trying to proxy everything as a websocket. You need two stanzas, one for `/allmon3/ws` that proxies as a websocket and then a less-specific `/allmon3` that proxies everything else as normal HTTP/2 or HTTP/1.1.

**Comment by K1WIZ** [comment]
I changed the nginx reverse proxy config to be:

`
server {
    listen 80;
    server_name hamhub.wizworks.net;

    location /allmon3/ws/ {
        proxy_pass http://10.0.1.165:80;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /allmon3/ {
        proxy_pass http://10.0.1.165:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

server {
    listen 443 ssl;
    server_name hamhub.wizworks.net;

    ssl_certificate /etc/nginx/certs/prox-selfsigned.crt;
    ssl_certificate_key /etc/nginx/certs/prox-selfsigned.key;

    location /allmon3/ws/ {
        proxy_pass http://10.0.1.165:80;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /allmon3/ {
        proxy_pass http://10.0.1.165:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
`

That should work based on what has been suggested, but there is no change in behaviour.

**Comment by jxmx** [comment]
I have something similar setup at home that was offline. I checked it and it continues to work just fine. You can see it at https://ke8ldh.ww8tf.club. Here's the entirety of the nginx configuration:

```
server {
    listen       443 ssl http2;
    listen       [::]:443 ssl http2;
    server_name  ke8ldh.ww8tf.club ke8ldh.mfamily.org;
    root         /usr/share/nginx/html;
    ssl_certificate /etc/letsencrypt/live/ke8ldh.ww8tf.club/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/ke8ldh.ww8tf.club/privkey.pem; # managed by Certbot
    ssl_session_cache shared:SSL:1m;
    ssl_session_timeout  10m;
    ssl_prefer_server_ciphers on;

    location / {
                proxy_pass http://172.17.16.60;
                include proxy_params;
    }

        location /allmon3/ws {
                proxy_pass http://172.17.16.60;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 86400;
        }

    add_header Strict-Transport-Security "max-age=31536000;" always;
}

```

**Comment by K1WIZ** [comment]
@jxmx This line in your config:
`root         /usr/share/nginx/html;`

Leads me to believe this is nginx running on the same box running allmon3, and not exactly the same thing as I'm doing here?  (a true separate nginx reverse proxy).  Let me know if I interpreted this incorrectly.

In my case, the box running allmon3 is running apache2

I have an nginx reverse proxy box in front of it, to (attempt) to make it publicly available.  This nginx box also does reverse proxying for all other web applications on this LAN, and those all work just fine when called externally.

The access chain is something like this:
cloudflare (Proxied DNS A record to my public IP) ---> nginx rev proxy (exposed on 443 on firewall) ----> inside LAN web application servers (one of which includes the debian 12 box running node 60454 and allmon3).

**Comment by jxmx** [comment]
No, you are assuming incorrectly. That configuration snippet is from a server running Nginx exclusively to reverse-proxy a ton of sites into my home infrastructure (14 of them in fact). That host's internal IP 172.17.16.36. The ASL3 node it's proxying to is 172.17.16.60. It's running a stock/standard ASL3 installation which includes Allmon3 running on Apache2. It's exactly what you're describing sans the Cloudflare part. I don't use Cloudflare.

**Comment by K1WIZ** [comment]
@jxmx 

Ok thanks for confirming.   I adjusted my configuration to match how yours was setup and I still see no change in behaviour.  Even after clearing browser cache, etc.   config is now:

`server {
    listen       443 ssl http2;
    #listen       [::]:443 ssl http2;
    server_name  hamhub.wizworks.net;
    root         /usr/share/nginx/html;
    ssl_certificate /etc/nginx/certs/prox-selfsigned.crt;
    ssl_certificate_key /etc/nginx/certs/prox-selfsigned.key;
    #ssl_session_cache shared:SSL:1m;
    ssl_session_timeout  10m;
    ssl_prefer_server_ciphers on;

    location / {
                proxy_pass http://10.0.1.165;
                include proxy_params;
    }

        location /allmon3/ws {
                proxy_pass http://10.0.1.165;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 86400;
        }

    #add_header Strict-Transport-Security "max-age=31536000;" always;
}`

**Comment by jxmx** [comment]
I would suggest dropping Cloudflare, pointing your DNS to your router and get that working first. I would assume you have something else in your nginx configuration that is interfering, perhaps in the `proxy_params` file.

**Comment by K1WIZ** [comment]
@jxmx I would prefer not to drop cloudflare.  I generally use them for DDos protection, as well as public SSL termination, needing only a long term private SSL cert on the nginx rev proxy.   Makes it stupid simple to do away with SSL headaches for multiple domains I host behind the CF/nginx layers.   

To temporarily cut out cloudflare, I entered this in my /etc/hosts file:
10.0.1.150 hamhub.wizworks.net

which sends all local browser traffic to the nginx rev proxy box on the LAN.   

My proxy_params contains:
`proxy_set_header Host $http_host;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $scheme;`

All other web apps work just fine (even those I have which require websockets, like uptime kuma for example:
https://status.wizworks.net/status/local

Allmon3 just isn't playing ball here:
https://hamhub.wizworks.net/allmon3

I've 3 other web apps which employ the use of web sockets, and allmon3 just refuses to work through the CF/Nginx rev proxy no matter what I do.

**Comment by jxmx** [comment]
You're not even getting to the websocket part. The full screen would be displayed and you'd only have an error in the table that the socket is closed. That means that the standard HTTP requests aren't being properly fulfilled to build the UI screen and start the sock listeners. I note that you're one release of code behind and I wonder if Cloudflare is behaving oddly over #237. Try upgrading to the latest version (1.3.2) or the code at in HEAD/develop and see if it's still a problem.

**Comment by K1WIZ** [comment]
@jxmx 

Installed the update:

`
Saving to: ‘allmon3_1.3.2-2.deb12_all.deb’

allmon3_1.3.2-2.deb12_all.deb    100%[==========================================================>]   3.43M  --.-KB/s    in 0.07s   

2024-08-08 15:28:49 (45.9 MB/s) - ‘allmon3_1.3.2-2.deb12_all.deb’ saved [3598904/3598904]

root@ASL3:~# dpkg -i allmon3_1.3.2-2.deb12_all.deb 
(Reading database ... 84251 files and directories currently installed.)
Preparing to unpack allmon3_1.3.2-2.deb12_all.deb ...
Unpacking allmon3 (1.3.2-2.deb12) over (1.3.1-2.deb12) ...
Setting up allmon3 (1.3.2-2.deb12) ...

Configuration file '/etc/allmon3/web.ini'
 ==> Modified (by you or by a script) since installation.
 ==> Package distributor has shipped an updated version.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** web.ini (Y/I/N/O/D/Z) [default=N] ? 
apache2_invoke proxy_http: already enabled
apache2_invoke proxy_wstunnel: already enabled
apache2_invoke rewrite: already enabled
apache2_invoke allmon3: already enabled
Processing triggers for man-db (2.11.2-2) ...
root@ASL3:~#
`

still showing a blank dashboard at https://hamhub.wizworks.net/allmon3

Anything else I can try?   some curls maybe?   If you give me some curl or other diagnostic stuff to try, I'll be happy to respond with output.

**Comment by jxmx** [comment]
Do you have some sort of caching enable? This URL https://hamhub.wizworks.net/allmon3/master/ui/custom is still returning the HTTP 400 error that was fixed in #237.

```
$ wget -O- https://hamhub.wizworks.net/allmon3/master/ui/custom
--2024-08-08 15:36:50--  https://hamhub.wizworks.net/allmon3/master/ui/custom
Resolving hamhub.wizworks.net (hamhub.wizworks.net)... 2606:4700:3032::ac43:a3f2, 2606:4700:3035::6815:3194, 104.21.49.148, ...
Connecting to hamhub.wizworks.net (hamhub.wizworks.net)|2606:4700:3032::ac43:a3f2|:443... connected.
HTTP request sent, awaiting response... 400 Bad Request
2024-08-08 15:36:50 ERROR 400: Bad Request.
```

**Comment by K1WIZ** [comment]
CF does do some caching, but I just enabled development mode on the domain which completely bypasses and disables any CF caching.   

I do report the same result even after disabling any caching at CF:

` 
john@john-desktop:~$ wget -O- https://hamhub.wizworks.net/allmon3/master/ui/custom
--2024-08-08 15:41:14--  https://hamhub.wizworks.net/allmon3/master/ui/custom
Resolving hamhub.wizworks.net (hamhub.wizworks.net)... 172.67.163.242, 104.21.49.148, 2606:4700:3035::6815:3194, ...
Connecting to hamhub.wizworks.net (hamhub.wizworks.net)|172.67.163.242|:443... connected.
HTTP request sent, awaiting response... 400 Bad Request
2024-08-08 15:41:14 ERROR 400: Bad Request.
`

**Comment by jxmx** [comment]
I deleted the last comment because the url is `/allmon3/master/ui/custom/menu` and it's working fine.

**Comment by K1WIZ** [comment]
@jxmx 
I concur:

`john@john-desktop:~$ wget -O- https://hamhub.wizworks.net/allmon3/master/ui/custom/menu
--2024-08-08 15:45:37--  https://hamhub.wizworks.net/allmon3/master/ui/custom/menu
Resolving hamhub.wizworks.net (hamhub.wizworks.net)... 104.21.49.148, 172.67.163.242, 2606:4700:3032::ac43:a3f2, ...
Connecting to hamhub.wizworks.net (hamhub.wizworks.net)|104.21.49.148|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 18 [text/json]
Saving to: ‘STDOUT’

-                                  0%[                                                           ]       0  --.-KB/s               {-                                100%[==========================================================>]      18  --.-KB/s    in 0s      

2024-08-08 15:45:37 (8.26 MB/s) - written to stdout [18/18]`

anything else I can try?

**Comment by jxmx** [comment]
It's definitely something with your reverse proxy or Cloudflare breaking the code

![image](https://github.com/user-attachments/assets/401c1ed4-62b2-4bd7-831f-0b02cade16b3)

The browser isn't even firing on the first JavaScript element. If you look at `index.js` on line 27:

```
// Hook page show
window.addEventListener('pageshow', pageLoad);
```

If you open the debugger console and just type `pageLoad();` and execute that command. Everything will work.

This isn't firing because something in your HTTP stack is breaking the client from reaching the "pageshow" status. I note that Cloudflare is injecting a bunch of JavaScript garbage into the page:

![image](https://github.com/user-attachments/assets/61e15058-473e-4ada-914c-57c23c718705)

**Comment by jxmx** [comment]
As a test, try changing line 27 of `index.js` to this:

```
window.addEventListener(`load`, pageLoad);
```

**Comment by jxmx** [comment]
The problem with using "load" instead of "pageshow" is caching can cause "load" not to fire because the content is already "loaded".

**Comment by K1WIZ** [comment]
@jxmx 

changed in index.js:

![image](https://github.com/user-attachments/assets/7c6d6d9b-de70-4122-9b53-442a5af7cde7)


refreshed the page but saw no change

**Comment by jxmx** [comment]
What if you change it to:

```
window.onload = pageLoad;
```

**Comment by K1WIZ** [comment]
@jxmx 
just before your last comment, I did fire this up in a virtual desktop and going through cloudflare after the first change to index.js.  here's what I see on the virtual desktop:

![image](https://github.com/user-attachments/assets/0ea2077c-a2f7-40d5-b2d0-4d233bb47178)

this is going through CF and nginx.  Let me nuke my cache on the other browser.  and I'll report back.

**Comment by K1WIZ** [comment]
@jxmx ok after nuking cache on my primary workstation completely, I can now fully load the allmon3 dashboard.   Also took CF out of development mode and it still seems to work.   

Do you still want me to try the `window.onload = pageLoad;` mod?

**Comment by K1WIZ** [comment]
@jxmx I spoke too soon.   after a short while and refreshing the page, broken dashboard again.   going to try the `window.onload = pageLoad;` mod.

**Comment by jxmx** [comment]
This is definitely something with your setup/configuration then. Very odd.

**Comment by jxmx** [comment]
However I fully expect it's Cloudflare goofing up stuff.

**Comment by K1WIZ** [comment]
Testing these changed cloudflare settings:

3. Check for Minification and Optimization Issues
Cloudflare offers features like Auto Minification and Rocket Loader which can sometimes cause issues with JavaScript.

Disable Auto Minification:

Go to Speed > Optimization.
Under Auto Minify, uncheck JavaScript.
Disable Rocket Loader:

Go to Speed > Optimization.
Find Rocket Loader and set it to Off.

**Comment by K1WIZ** [comment]
@jxmx 

Ok so disabled the minification and Rocket Loader features (under speed) in cloudflare.   cleared cache and refreshed to find the dashboard working.   I'll close the issue.  Thank you for your help.

**Comment by K1WIZ** [comment]
closing due to interference from cloudflare optimization machinery.
