### ISSUE TITLE
custom.css changes have no affect

### ISSUE THREAD

**Issue by pcpackrat** [AllStarLink/Allmon3#246]
editing /etc/allmon3/custom.css does not have any affect on page colors.

Running v1.3.1 on Debian 12

Restarted allmon3 after changes made just in case

**Comment by pcpackrat** [comment]
Updating to 1.3.2 fixed it.

**Comment by Pross** [comment]
> Updating to 1.3.2 fixed it.

Thats because the current version is added to all assets to bust through browser caching.
`192.168.1.212/allmon3/css/custom.css?v=1.3.3` If you had hard refreshed the browser or had dev tools open you would have seen your changes
