### ISSUE TITLE
AMI connection every 10 seconds

### ISSUE THREAD

**Issue by tsawyer** [AllStarLink/Allmon3#26]
@InterLinked1 tells me the AMI is for long term connections. I'm thinking statmon should connect and stay connected for as long as it's running. However, I see a connect and disconnect every 10 seconds. Is that intended?
```
[2023-03-07 06:36:52.809]     -- Remote UNIX connection disconnected
[2023-03-07 06:37:03.056]     -- Remote UNIX connection
[2023-03-07 06:37:03.060]     -- Remote UNIX connection disconnected
[2023-03-07 06:37:13.316]     -- Remote UNIX connection
[2023-03-07 06:37:13.320]     -- Remote UNIX connection disconnected
```

**Comment by InterLinked1** [comment]
These look like CLI connections, not AMI connections

**Comment by tsawyer** [comment]
My mistake. I stopped statmon but they're still there. Is there a way to tell what is doing that?

**Comment by InterLinked1** [comment]
I don't know of a good way off hand, no. It's something on the local machine itself (or proxied through the local machine). In theory we could add code to print out the commands being run, which might offer a clue.

**Comment by tsawyer** [comment]
Shut down cron and statmon but it was still there. Only a server reboot cleared it.
