### ISSUE TITLE
More Echolink Parsing Errors?

### ISSUE THREAD

**Issue by jxmx** [AllStarLink/Allmon3#261]
https://community.allstarlink.org/t/echolink-node-numbers-not-displaying-correctly/22252/15

**Comment by knobby4444** [comment]
I joined my node with echo and the table disappeared in allmon3 just now.  There is one other node connected that is not echo.  Getting this error in allmon3 debug log:

EBUG: (asl_allmon.ami_conn) response >> Response: Error  Message: Command output follows  Output: Error: Entry for 871450 not found!  Output: Command 'echolink dbget nodename 871450' failed.    

In the allstarlink.org nodelist, echo node number is 3871450.
At the echolink lookup webpage, my callsign shows 302884 which matches what I have in my own records.  https://www.echolink.org/validation/node_lookup.jsp

**Comment by knobby4444** [comment]
For everyone's reference, the magic happens here:

/usr/lib/python3/dist-packages/asl_allmon/ami_parser/__init__.py

starting around line 140

**Comment by jxmx** [comment]
Interesting. Can you run `echolink dbget nodename 871450` from the CLI? That's saying that your node doesn't have the full Echolink database. Obviously Allmon3 shouldn't blow up over that problem, but I'm surprised it's happening at all...

**Comment by knobby4444** [comment]
Connected to Asterisk 20.10.0+asl3-3.1.0-1.deb12 currently running on allstar-3 (pid = 104723)
allstar-3*CLI> echolink dbget nodename 871450
Error: Entry for 871450 not found!
Command 'echolink dbget nodename 871450' failed.
allstar-3*CLI>

**Comment by knobby4444** [comment]
My correct nodenumber fails as well:

allstar-3*CLI> echolink dbget nodename 302884
Error: Entry for 302884 not found!
Command 'echolink dbget nodename 302884' failed.
allstar-3*CLI>

**Comment by jxmx** [comment]
How long was node 302884 logged in before you asked for that? It does take the Echolink DB awhile to propagate.

**Comment by knobby4444** [comment]
I feel like I previously heard this is fine, but I get this in the CLI when echo connects:

[2024-12-17 09:43:12.070] WARNING[139183][C-00000013]: func_channel.c:574 func_channel_read: Unknown or unavailable item requested: 'peerip'

I probably wasn't logged in to echo when I tried earlier.  Just logged in and tried again, it's been 8 minutes and still failing, but if I lookup the echo node hosted on the allstar node I'm logging into, that does work:

allstar-3*CLI> echolink dbget nodename 302884
Error: Entry for 302884 not found!
Command 'echolink dbget nodename 302884' failed.
allstar-3*CLI> echolink dbget nodename 640127
640127|K5FD-R|209.65.151.206
allstar-3*CLI>

**Comment by knobby4444** [comment]
After I connected again, it picked up another node number 

DEBUG: (asl_allmon.ami_conn) response >> Response: Error  Message: Command output follows  Output: Error: Entry for 101425 not found!  Output: Command 'echolink dbget nodename 101425' failed.

**Comment by knobby4444** [comment]
Lookup fails

**Comment by jxmx** [comment]
Can you provide more of the output around that debug message? The code should be setting "No database information". Do you have a line that says "Invalid response about echolink...".

**Comment by knobby4444** [comment]
DEBUG: (asl_allmon.ami_conn) command >> ACTION: RptStatus COMMAND: XStat NODE: 49520  ActionID: b8d629ef-8ea4-4996-a0d4-5a8cd54772be  
DEBUG: (asl_allmon.ami_conn) response >> Response: Success  Node: 49520  Conn: 47922     70.188.192.144      0           IN         03:04:34            ESTABLISHED           Conn: KG5DRT-1  192.168.10.61       0           IN         01:34:28            ESTABLISHED           Conn: 3101425                       1           IN         00:14:00            ESTABLISHED           LinkedNodes: T3101425, T47922, TKG5DRT-1  Var: RPT_NUMLINKS=3  Var: RPT_LINKS=3,T47922,T3101425,TKG5DRT-1  Var: RPT_NUMALINKS=3  Var: RPT_ALINKS=3,47922TU,3101425TU,KG5DRT-1TU  Var: RPT_ETXKEYED=0  Var: RPT_RXKEYED=0  Var: RPT_AUTOPATCHUP=0  Var: RPT_TXKEYED=0  parrot_ena: 0  sys_ena: 0  tot_ena: 0  link_ena: 0  patch_ena: 0  patch_state: 4  sch_ena: 0  user_funs: 0  tail_type: 0  iconns: 0  tot_state: 2  ider_state: 2  tel_mode: 0    
DEBUG: (asl_allmon.ami_parser) enter get_echolink_name(3101425)
DEBUG: (asl_allmon.ami_conn) enter asl_cmd_response()
DEBUG: (asl_allmon.ami_conn) command >> ACTION: COMMAND COMMAND: echolink dbget nodename 101425  ActionID: db918ecc-9d3d-43b2-a214-61a229de0fa9  
DEBUG: (asl_allmon.ami_conn) response >> Response: Error  Message: Command output follows  Output: Error: Entry for 101425 not found!  Output: Command 'echolink dbget nodename 101425' failed.    
DEBUG: (asl_allmon.ami_parser) exiting get_echolink_name(101425)
ERROR: (asl_allmon.allmon3_ws_status) ERROR: list index out of range
DEBUG: (asl_allmon.allmon3_ws_status) Node 49520 - status_connections: 2
DEBUG: (asl_allmon.allmon3_ws_status) broadcasting 49520
DEBUG: (asl_allmon.ami_parser) entering parse_xstat(49520)
DEBUG: (asl_allmon.ami_conn) enter asl_cmd_response()
DEBUG: (asl_allmon.ami_conn) command >> ACTION: RptStatus COMMAND: XStat NODE: 49520  ActionID: e0d2ff1b-525c-49a1-85d8-ebd280e91404  
DEBUG: (asl_allmon.ami_conn) response >> Response: Success  Node: 49520  Conn: 47922     70.188.192.144      0           IN         03:04:34            ESTABLISHED           Conn: KG5DRT-1  192.168.10.61       0           IN         01:34:28            ESTABLISHED           Conn: 3101425                       1           IN         00:14:00            ESTABLISHED           LinkedNodes: T3101425, T47922, TKG5DRT-1  Var: RPT_NUMLINKS=3  Var: RPT_LINKS=3,T47922,T3101425,TKG5DRT-1  Var: RPT_NUMALINKS=3  Var: RPT_ALINKS=3,47922TU,3101425TU,KG5DRT-1TU  Var: RPT_ETXKEYED=0  Var: RPT_RXKEYED=0  Var: RPT_AUTOPATCHUP=0  Var: RPT_TXKEYED=0  parrot_ena: 0  sys_ena: 0  tot_ena: 0  link_ena: 0  patch_ena: 0  patch_state: 4  sch_ena: 0  user_funs: 0  tail_type: 0  iconns: 0  tot_state: 2  ider_state: 2  tel_mode: 0    
DEBUG: (asl_allmon.ami_parser) enter get_echolink_name(3101425)
DEBUG: (asl_allmon.ami_conn) enter asl_cmd_response()
DEBUG: (asl_allmon.ami_conn) command >> ACTION: COMMAND COMMAND: echolink dbget nodename 101425  ActionID: 71b3688e-553e-4f4e-813f-759127ca40ff  
DEBUG: (asl_allmon.ami_conn) response >> Response: Error  Message: Command output follows  Output: Error: Entry for 101425 not found!  Output: Command 'echolink dbget nodename 101425' failed.    
DEBUG: (asl_allmon.ami_parser) exiting get_echolink_name(101425)
ERROR: (asl_allmon.allmon3_ws_status) ERROR: list index out of range
DEBUG: (asl_allmon.allmon3_ws_status) Node 49520 - status_connections: 2
DEBUG: (asl_allmon.allmon3_ws_status) broadcasting 49520
DEBUG: (asl_allmon.ami_parser) entering parse_xstat(49520)
DEBUG: (asl_allmon.ami_conn) enter asl_cmd_response()
DEBUG: (asl_allmon.ami_conn) command >> ACTION: RptStatus COMMAND: XStat NODE: 49520  ActionID: 6197b67a-0489-4444-a5d6-df5bf7061ef7  
DEBUG: (asl_allmon.ami_conn) response >> Response: Success  Node: 49520  Conn: 47922     70.188.192.144      0           IN         03:04:34            ESTABLISHED           Conn: KG5DRT-1  192.168.10.61       0           IN         01:34:28            ESTABLISHED           Conn: 3101425                       1           IN         00:14:00            ESTABLISHED           LinkedNodes: T3101425, T47922, TKG5DRT-1  Var: RPT_NUMLINKS=3  Var: RPT_LINKS=3,T47922,T3101425,TKG5DRT-1  Var: RPT_NUMALINKS=3  Var: RPT_ALINKS=3,47922TU,3101425TU,KG5DRT-1TU  Var: RPT_ETXKEYED=0  Var: RPT_RXKEYED=0  Var: RPT_AUTOPATCHUP=0  Var: RPT_TXKEYED=0  parrot_ena: 0  sys_ena: 0  tot_ena: 0  link_ena: 0  patch_ena: 0  patch_state: 4  sch_ena: 0  user_funs: 0  tail_type: 0  iconns: 0  tot_state: 2  ider_state: 2  tel_mode: 0    
DEBUG: (asl_allmon.ami_parser) enter get_echolink_name(3101425)
DEBUG: (asl_allmon.ami_conn) enter asl_cmd_response()
DEBUG: (asl_allmon.ami_conn) command >> ACTION: COMMAND COMMAND: echolink dbget nodename 101425  ActionID: 1f7ec2a6-eac2-404b-a749-eb507d863eee  
DEBUG: (asl_allmon.ami_conn) response >> Response: Error  Message: Command output follows  Output: Error: Entry for 101425 not found!  Output: Command 'echolink dbget nodename 101425' failed.    
DEBUG: (asl_allmon.ami_parser) exiting get_echolink_name(101425)
ERROR: (asl_allmon.allmon3_ws_status) ERROR: list index out of range
DEBUG: (asl_allmon.allmon3_ws_status) Node 49520 - status_connections: 2
DEBUG: (asl_allmon.allmon3_ws_status) broadcasting 49520
DEBUG: (asl_allmon.ami_parser) entering parse_xstat(49520)
DEBUG: (asl_allmon.ami_conn) enter asl_cmd_response()
DEBUG: (asl_allmon.ami_conn) command >> ACTION: RptStatus COMMAND: XStat NODE: 49520  ActionID: 44e120ca-c73c-46ad-8bab-97ae0240eb47  
DEBUG: (asl_allmon.ami_conn) response >> Response: Success  Node: 49520  Conn: 47922     70.188.192.144      0           IN         03:04:34            ESTABLISHED           Conn: KG5DRT-1  192.168.10.61       0           IN         01:34:28            ESTABLISHED           Conn: 3101425                       1           IN         00:14:00            ESTABLISHED           LinkedNodes: T3101425, T47922, TKG5DRT-1  Var: RPT_NUMLINKS=3  Var: RPT_LINKS=3,T47922,T3101425,TKG5DRT-1  Var: RPT_NUMALINKS=3  Var: RPT_ALINKS=3,47922TU,3101425TU,KG5DRT-1TU  Var: RPT_ETXKEYED=0  Var: RPT_RXKEYED=0  Var: RPT_AUTOPATCHUP=0  Var: RPT_TXKEYED=0  parrot_ena: 0  sys_ena: 0  tot_ena: 0  link_ena: 0  patch_ena: 0  patch_state: 4  sch_ena: 0  user_funs: 0  tail_type: 0  iconns: 0  tot_state: 2  ider_state: 2  tel_mode: 0    
DEBUG: (asl_allmon.ami_parser) enter get_echolink_name(3101425)
DEBUG: (asl_allmon.ami_conn) enter asl_cmd_response()
DEBUG: (asl_allmon.ami_conn) command >> ACTION: COMMAND COMMAND: echolink dbget nodename 101425  ActionID: 99e66599-b2ac-47c4-8bda-89ce99afc55a  
DEBUG: (asl_allmon.ami_conn) response >> Response: Error  Message: Command output follows  Output: Error: Entry for 101425 not found!  Output: Command 'echolink dbget nodename 101425' failed.    
DEBUG: (asl_allmon.ami_parser) exiting get_echolink_name(101425)
ERROR: (asl_allmon.allmon3_ws_status) ERROR: list index out of range
DEBUG: (asl_allmon.allmon3_ws_status) Node 49520 - status_connections: 2
DEBUG: (asl_allmon.allmon3_ws_status) broadcasting 49520
DEBUG: (asl_allmon.ami_parser) entering parse_xstat(49520)
DEBUG: (asl_allmon.ami_conn) enter asl_cmd_response()
DEBUG: (asl_allmon.ami_conn) command >> ACTION: RptStatus COMMAND: XStat NODE: 49520  ActionID: 05fa606e-6d0d-4fb6-9f60-84532a015d52  
DEBUG: (asl_allmon.ami_conn) response >> Response: Success  Node: 49520  Conn: 47922     70.188.192.144      0           IN         03:04:34            ESTABLISHED           Conn: KG5DRT-1  192.168.10.61       0           IN         01:34:28            ESTABLISHED           Conn: 3101425                       1           IN         00:14:00            ESTABLISHED           LinkedNodes: T3101425, T47922, TKG5DRT-1  Var: RPT_NUMLINKS=3  Var: RPT_LINKS=3,T47922,T3101425,TKG5DRT-1  Var: RPT_NUMALINKS=3  Var: RPT_ALINKS=3,47922TU,3101425TU,KG5DRT-1TU  Var: RPT_ETXKEYED=0  Var: RPT_RXKEYED=0  Var: RPT_AUTOPATCHUP=0  Var: RPT_TXKEYED=0  parrot_ena: 0  sys_ena: 0  tot_ena: 0  link_ena: 0  patch_ena: 0  patch_state: 4  sch_ena: 0  user_funs: 0  tail_type: 0  iconns: 0  tot_state: 2  ider_state: 2  tel_mode: 0    
DEBUG: (asl_allmon.ami_parser) enter get_echolink_name(3101425)
DEBUG: (asl_allmon.ami_conn) enter asl_cmd_response()
DEBUG: (asl_allmon.ami_conn) command >> ACTION: COMMAND COMMAND: echolink dbget nodename 101425  ActionID: 8cf5aea2-add0-4eb9-a6d0-ff2f06115800  
DEBUG: (asl_allmon.ami_conn) response >> Response: Error  Message: Command output follows  Output: Error: Entry for 101425 not found!  Output: Command 'echolink dbget nodename 101425' failed.    
DEBUG: (asl_allmon.ami_parser) exiting get_echolink_name(101425)
ERROR: (asl_allmon.allmon3_ws_status) ERROR: list index out of range
DEBUG: (asl_allmon.allmon3_ws_status) Node 49520 - status_connections: 2
DEBUG: (asl_allmon.allmon3_ws_status) broadcasting 49520
DEBUG: (asl_allmon.ami_parser) entering parse_xstat(49520)
DEBUG: (asl_allmon.ami_conn) enter asl_cmd_response()
DEBUG: (asl_allmon.ami_conn) command >> ACTION: RptStatus COMMAND: XStat NODE: 49520  ActionID: 6440e7eb-b2a9-47d2-9c94-2e7696e2eac5  
DEBUG: (asl_allmon.ami_conn) response >> Response: Success  Node: 49520  Conn: 47922     70.188.192.144      0           IN         03:04:34            ESTABLISHED           Conn: KG5DRT-1  192.168.10.61       0           IN         01:34:28            ESTABLISHED           Conn: 3101425                       1           IN         00:14:00            ESTABLISHED           LinkedNodes: T3101425, T47922, TKG5DRT-1  Var: RPT_NUMLINKS=3  Var: RPT_LINKS=3,T47922,T3101425,TKG5DRT-1  Var: RPT_NUMALINKS=3  Var: RPT_ALINKS=3,47922TU,3101425TU,KG5DRT-1TU  Var: RPT_ETXKEYED=0  Var: RPT_RXKEYED=0  Var: RPT_AUTOPATCHUP=0  Var: RPT_TXKEYED=0  parrot_ena: 0  sys_ena: 0  tot_ena: 0  link_ena: 0  patch_ena: 0  patch_state: 4  sch_ena: 0  user_funs: 0  tail_type: 0  iconns: 0  tot_state: 2  ider_state: 2  tel_mode: 0    
DEBUG: (asl_allmon.ami_parser) enter get_echolink_name(3101425)
DEBUG: (asl_allmon.ami_conn) enter asl_cmd_response()
DEBUG: (asl_allmon.ami_conn) command >> ACTION: COMMAND COMMAND: echolink dbget nodename 101425  ActionID: aaf7a5ef-2f07-4210-813e-729f242c767f  
DEBUG: (asl_allmon.ami_conn) response >> Response: Error  Message: Command output follows  Output: Error: Entry for 101425 not found!  Output: Command 'echolink dbget nodename 101425' failed.    
DEBUG: (asl_allmon.ami_parser) exiting get_echolink_name(101425)
ERROR: (asl_allmon.allmon3_ws_status) ERROR: list index out of range
DEBUG: (asl_allmon.allmon3_ws_status) Node 49520 - status_connections: 2
DEBUG: (asl_allmon.allmon3_ws_status) broadcasting 49520
DEBUG: (asl_allmon.ami_parser) entering parse_xstat(49520)
DEBUG: (asl_allmon.ami_conn) enter asl_cmd_response()
DEBUG: (asl_allmon.ami_conn) command >> ACTION: RptStatus COMMAND: XStat NODE: 49520  ActionID: c2b71d1d-c9e7-4dd5-9141-a571ae99112b  
DEBUG: (asl_allmon.ami_conn) response >> Response: Success  Node: 49520  Conn: 47922     70.188.192.144      0           IN         03:04:34            ESTABLISHED           Conn: KG5DRT-1  192.168.10.61       0           IN         01:34:28            ESTABLISHED           Conn: 3101425                       1           IN         00:14:00            ESTABLISHED           LinkedNodes: T3101425, T47922, TKG5DRT-1  Var: RPT_NUMLINKS=3  Var: RPT_LINKS=3,T47922,T3101425,TKG5DRT-1  Var: RPT_NUMALINKS=3  Var: RPT_ALINKS=3,47922TU,3101425TU,KG5DRT-1TU  Var: RPT_ETXKEYED=0  Var: RPT_RXKEYED=0  Var: RPT_AUTOPATCHUP=0  Var: RPT_TXKEYED=0  parrot_ena: 0  sys_ena: 0  tot_ena: 0  link_ena: 0  patch_ena: 0  patch_state: 4  sch_ena: 0  user_funs: 0  tail_type: 0  iconns: 0  tot_state: 2  ider_state: 2  tel_mode: 0    
DEBUG: (asl_allmon.ami_parser) enter get_echolink_name(3101425)
DEBUG: (asl_allmon.ami_conn) enter asl_cmd_response()
DEBUG: (asl_allmon.ami_conn) command >> ACTION: COMMAND COMMAND: echolink dbget nodename 101425  ActionID: fa3bbf61-cd0c-4a17-8248-b0e024fabfc2  
DEBUG: (asl_allmon.ami_conn) response >> Response: Error  Message: Command output follows  Output: Error: Entry for 101425 not found!  Output: Command 'echolink dbget nodename 101425' failed.    
DEBUG: (asl_allmon.ami_parser) exiting get_echolink_name(101425)
ERROR: (asl_allmon.allmon3_ws_status) ERROR: list index out of range
DEBUG: (asl_allmon.allmon3_ws_status) Node 49520 - status_connections: 2
DEBUG: (asl_allmon.allmon3_ws_status) broadcasting 49520
DEBUG: (asl_allmon.ami_parser) entering parse_xstat(49520)
DEBUG: (asl_allmon.ami_conn) enter asl_cmd_response()
DEBUG: (asl_allmon.ami_conn) command >> ACTION: RptStatus COMMAND: XStat NODE: 49520  ActionID: c85ab0af-c522-4f96-8d0c-27113fd2c16f

**Comment by knobby4444** [comment]
I'm guessing this is happening instead of the invalid response:

ERROR: (asl_allmon.allmon3_ws_status) ERROR: list index out of range

**Comment by jxmx** [comment]
I'm slightly confused why you're seeing that. I may need to setup some time for you to connect to a test node on my system to see what's really going on. Can you try something? In `/usr/lib/python3/dist-packages/asl_allmon/ami_parser/__init__.py` can you comment out these lines starting at line 174:

```python

                # Connections of 3nnnnnn are Echolink
                elif re.match(r'^3[0-9]{6}$', nname):
                    ename = await self.get_echolink_name(nname)
                    node_conns[nname]["DESC"] = ename
```

After commenting that out, t ry to run it in debug mode again.

**Comment by jetski28** [comment]
I'm also having the same "list index out of range" error on Allmon3 version 1.4.1

After commenting out those 3 lines the connection list loads but all the echolink connections show as "Private or Unavailable". One of the two echolink nodes fails a lookup with the echolink dbget command in asterisks CLI.

**Comment by knobby4444** [comment]
Looks like the same here, allmon3 working with wrong node number in the UI after commenting the echo lookup
![image](https://github.com/user-attachments/assets/4c69cac8-4094-4b87-887b-674262c986ef)

**Comment by jxmx** [comment]
But are the Echolink IDs accurate (other than the leading 3)?

**Comment by knobby4444** [comment]
Negative.  The screenshot above is showing the 3rd node number I've received since yesterday's testing.  And none of them have looked up successfully, with or without the 3.  Neither does my correct echo node number, with or without 3.

**Comment by jxmx** [comment]
Can you be more specific? Are you saying that Asterisk is reporting **random** IDs for your Echolink connection? What is your **expected** Echolink ID? When connected with Echolink, paste in the output of `rpt nodes NODE` and `rpt xnode NODE` please.

**Comment by knobby4444** [comment]
I believe I get a random echo node number each time I disconnect and reconnect.  Same as I described at the beginning of this thread.  And other echo users seem to get random node numbers the same way.  My echo node number per the echo website and my own records is 302884.  In the output below, I"m the 3166094 node:

allstar-3*CLI> rpt nodes 49520

************************* CONNECTED NODES *************************

T3166094, T47922

allstar-3*CLI> rpt xnode 49520
47922     70.188.192.144      0           IN         23:29:51            ESTABLISHED         ~3166094                       1           IN         00:02:49            ESTABLISHED         ~

T3166094, T47922

RPT_NUMLINKS=2
RPT_LINKS=2,T47922,T3166094
RPT_NUMALINKS=2
RPT_ALINKS=2,47922TU,3166094TU
RPT_ETXKEYED=0
RPT_RXKEYED=0
RPT_AUTOPATCHUP=0
RPT_TXKEYED=0

parrot_ena=0
sys_ena=1
tot_ena=1
link_ena=1
patch_ena=1
patch_state=4
sch_ena=1
user_funs=1
tail_type=0
iconns=1
tot_state=2
ider_state=2
tel_mode=0

allstar-3*CLI>

**Comment by knobby4444** [comment]
I disconnected and reconnected and it's a different number:

allstar-3*CLI> rpt nodes 49520

************************* CONNECTED NODES *************************

T3263216, T47922

allstar-3*CLI> rpt xnode 49520
47922     70.188.192.144      0           IN         23:32:56            ESTABLISHED         ~3263216                       1           IN         00:00:05            ESTABLISHED         ~

T3263216, T47922

RPT_NUMLINKS=2
RPT_LINKS=2,T47922,T3263216
RPT_NUMALINKS=2
RPT_ALINKS=2,47922TU,3263216TU
RPT_ETXKEYED=0
RPT_RXKEYED=0
RPT_AUTOPATCHUP=0
RPT_TXKEYED=0

parrot_ena=0
sys_ena=1
tot_ena=1
link_ena=1
patch_ena=1
patch_state=4
sch_ena=1
user_funs=1
tail_type=0
iconns=1
tot_state=2
ider_state=2
tel_mode=0

allstar-3*CLI>

**Comment by jxmx** [comment]
That's very interesting.... So there is an Allmon3 problem in that something is still choking on "node not found" errors from the Echolink database. But another issue Allmon3 can't solve is Echolink sending in randomized IDs.

**Comment by knobby4444** [comment]
I'm able to join another node, 45933 and the node number is correct in the allstarlink.org nodelist.  That node is hamvoip.

**Comment by jxmx** [comment]
Can you try joining N8EI-R node 2116 with Echolink so I can capture a debug output?

**Comment by jxmx** [comment]
```
[2024-12-18 10:11:48.429] DEBUG[760]: chan_echolink.c:3237 do_new_call: New Call - Callsign KG5DRT, IP Address 23.92.223.142, Node 198857, Name Jake.
```

**Comment by knobby4444** [comment]
Callsign is correct at least :), wroing IP and node

**Comment by jxmx** [comment]
```
[2024-12-18 10:11:48.429] DEBUG[760]: chan_echolink.c:3237 do_new_call: New Call - Callsign KG5DRT, IP Address 23.92.223.142, Node 1                            98857, Name Jake.
[2024-12-18 10:11:48.429] DEBUG[760]: chan_echolink.c:3402 el_reader: APRS out: )EL-N8EI-R!4103.60NE08140.80W0PHG0000/000000/000 On                             @ 1511 [1/20].
    -- Executing [2116@radio-secure:1] NoOp("echolink/el0-0", "Connect from node: 3198857") in new stack
    -- Executing [2116@radio-secure:2] NoOp("echolink/el0-0", "Connect to: 2116") in new stack
[2024-12-18 10:11:48.429] WARNING[49800][C-0000000b]: func_channel.c:574 func_channel_read: Unknown or unavailable item requested: '                            peerip'
    -- Executing [2116@radio-secure:3] NoOp("echolink/el0-0", "The Channel IP is ") in new stack
[2024-12-18 10:11:48.429] WARNING[49800][C-0000000b]: func_channel.c:574 func_channel_read: Unknown or unavailable item requested: '                            peerip'
    -- Executing [2116@radio-secure:4] GotoIf("echolink/el0-0", "0?connect") in new stack
    -- Executing [2116@radio-secure:5] GotoIf("echolink/el0-0", "1?denylist") in new stack
    -- Goto (radio-secure,2116,9)
    -- Executing [2116@radio-secure:9] GotoIf("echolink/el0-0", "0?:connect") in new stack
    -- Goto (radio-secure,2116,12)
    -- Executing [2116@radio-secure:12] Rpt("echolink/el0-0", "2116") in new stack
[2024-12-18 10:11:48.502] DEBUG[759]: chan_echolink.c:3186 el_register: Trying to register with Echolink server nasouth.echolink.org                            .
[2024-12-18 10:11:48.546] DEBUG[761]: chan_echolink.c:3128 el_directory: Trying to do directory download Echolink server nasouth.ech                            olink.org.
       > Received OK from Echolink server nasouth.echolink.org.
       > Received OK from Echolink server nasouth.echolink.org.
[2024-12-18 10:11:48.647] DEBUG[761]: chan_echolink.c:2943 do_el_directory: Sending: F280005248 to nasouth.echolink.org.
       > Directory completed downloading(partial,compressed), 460 records.
[2024-12-18 10:11:48.794] DEBUG[761]: chan_echolink.c:3079 do_el_directory: Got snapshot_id: 280012794
[2024-12-18 10:11:49.127] DEBUG[760]: chan_echolink.c:3485 el_reader: Channel echolink/el0-0 answering.
nickel*CLI> rpt xnode 2116
3198857                       1           IN         00:00:19            ESTABLISHED         ~

T3198857

RPT_NUMLINKS=1
RPT_LINKS=1,T3198857
RPT_NUMALINKS=1
RPT_ALINKS=1,3198857TU
RPT_AUTOPATCHUP=0
RPT_ETXKEYED=0
RPT_TXKEYED=0
RPT_RXKEYED=0

parrot_ena=0
sys_ena=1
tot_ena=1
link_ena=1
patch_ena=1
patch_state=4
sch_ena=1
user_funs=1
tail_type=0
iconns=1
tot_state=2
ider_state=2
tel_mode=2

nickel*CLI>
```

**Comment by jxmx** [comment]
> wroing IP

Is your Echolink client using an Echolink proxy? That's normally the default config.

**Comment by knobby4444** [comment]
Oh yes of course, I'm on android and using the defaults.

**Comment by knobby4444** [comment]
Looks like 'Relay' is the default setting on android, just connected via Public Proxy and it's the right node number in the allstarlink.org nodelist. 

Choices are:
Direct (failed)
Relay (wrong node number)
Public Proxy (seems good)
Custom Proxy (not tested)

**Comment by knobby4444** [comment]
That would explain why some people can connect fine and others it causes the issue.

**Comment by jxmx** [comment]
To confirm HamVOIP isn't a fluke can you connect to node 43211 and check your name on https://hub.w8wky.org?

**Comment by jxmx** [comment]
Sorry, that's W8WKY-R in Echolink terms...

**Comment by knobby4444** [comment]
Can only connect via Relay it seems, and everything looks correct there. Update, worked on Public Proxy 2nd try

**Comment by jxmx** [comment]
https://github.com/AllStarLink/app_rpt/issues/434

**Comment by knobby4444** [comment]
I uncommented the lines mentioned around 174 and allmon3 loads fine, when there is no Relay connection.

**Comment by jxmx** [comment]
Will please try this code: https://raw.githubusercontent.com/AllStarLink/Allmon3/refs/heads/fix_261/src/asl_allmon/ami_parser/__init__.py as a replacement for `/usr/lib/python3/dist-packages/asl_allmon/ami_parser/__init__.py `.

**Comment by knobby4444** [comment]
Node number correct, with the leading 3, no database info for descrip

**Comment by knobby4444** [comment]
Hmm, it did an apt upgrade, I guess I wasn't on the latest before, I re-replaced the __init__.py, but echo nodes are random again.

root@allstar-3:/usr/lib/python3/dist-packages/asl_allmon/ami_parser# asl-show-version 
********** AllStarLink [ASL] Version Info **********

OS            : Debian GNU/Linux 12 (bookworm)
OS Kernel     : 6.6.62+rpt-rpi-v8

Asterisk      : 20.10.0+asl3-3.1.0-1.deb12
ASL [app_rpt] : 3.1.0

Installed ASL packages :

  Package                         Version
  ==============================  ==============================
  allmon3                         1.4.1-1.deb12
  asl3                            3.6.0-1.deb
  asl3-asterisk                   2:20.10.0+asl3-3.1.0-1.deb12
  asl3-asterisk-config            2:20.10.0+asl3-3.1.0-1.deb12
  asl3-asterisk-modules           2:20.10.0+asl3-3.1.0-1.deb12
  asl3-menu                       1.10-1.deb12
  asl3-pi-appliance               1.8.1-1.deb12
  asl3-update-nodelist            1.5.1-1.deb12
  cockpit                         287.1-0+deb12u3
  cockpit-bridge                  287.1-0+deb12u3
  cockpit-networkmanager          287.1-0+deb12u3
  cockpit-packagekit              287.1-0+deb12u3
  cockpit-sosreport               287.1-0+deb12u3
  cockpit-storaged                287.1-0+deb12u3
  cockpit-system                  287.1-0+deb12u3
  cockpit-wifimanager             1.1.0-2.deb12
  cockpit-ws                      287.1-0+deb12u3
  dahdi                           1:3.1.0-2
  dahdi-dkms                      1:3.4.0-4+asl
  dahdi-linux                     1:3.4.0-4+asl
root@allstar-3:/usr/lib/python3/dist-packages/asl_allmon/ami_parser#

**Comment by jxmx** [comment]
The nodes will still be random. This would only fix the display not working at all. Now the random nodes may be "no info" or be the wrong callsign. That's a different issue.

**Comment by jxmx** [comment]
Commite 3190845 is an incomplete fix

**Comment by jxmx** [comment]
3190845..617ecc1 has a full fix.
