### ISSUE TITLE
Always reporting Initializing

### ISSUE THREAD

**Issue by tsawyer** [AllStarLink/Allmon3#29]
Always reporting Initializing on web and test client.

<img width="1497" alt="Screenshot 2023-03-09 at 8 50 28 AM" src="https://user-images.githubusercontent.com/1526362/224097200-fe0d13a7-45a9-49e0-8692-d90d5322a6a0.png">

**Comment by jxmx** [comment]
Which nodes is this on? Looking at your node 2509 you don't have the latest asl-statmon in /usr/local/bin there.

**Comment by jxmx** [comment]
See #32
