### ISSUE TITLE
Local Monitor

### ISSUE THREAD

**Issue by tsawyer** [AllStarLink/Allmon3#30]
Be sure to code for Local Monitor.
<img width="896" alt="Screenshot 2023-03-09 at 11 20 52 AM" src="https://user-images.githubusercontent.com/1526362/224132348-47f67b04-7fc6-43c3-8750-f98165b1a3e8.png">

**Comment by jxmx** [comment]
![image](https://user-images.githubusercontent.com/21324335/224200628-d57b220a-531d-4440-a884-1f17a0e119bb.png)

**Comment by jxmx** [comment]
See #32
