### ISSUE TITLE
JavaScript error allmon3.ini

### ISSUE THREAD

**Issue by W3KIT-910** [AllStarLink/Allmon3#34]
I am getting "could not parse /var/www/html/allmon3/api/allmon3.ini".

Do I need to place allmon3.ini in var/www/html/allmon3/api/?

per instruction I placed allmon3.ini in /usr/local/etc/

The error above goes away if I copy allmon3.ini and place it in /var/www/html/allmon3/api/

I also still have the "Initializing"  that does not goes away.

Thanks, Kit

**Comment by jxmx** [comment]
Need to make the API .ini configuration a multi-choice item in the code.

**Comment by jxmx** [comment]
@W3KIT-910 the Initializing issue was fixed last night. Make sure you're using the most recent asl-statmon.

**Comment by tsawyer** [comment]
Yes, you need to place an allmon3.ini in /var/www/html/allmom3/api/ but it needs a slightly different format than the ini for statmon. For example:
```
[12345]
monip=127.0.0.1
monport=6750
[54321]
monip=127.0.0.1
monport=6751
```

**Comment by jxmx** [comment]
https://github.com/AllStarLink/Allmon3/commit/04a01d1c09b848f747ecfe276e6a9f082210661f
https://github.com/AllStarLink/Allmon3/commit/170e6cbfbb1bf4aafe960bb3d1ad50616c83908e
https://github.com/AllStarLink/Allmon3/commit/df2e3b3b5237524fbcc77ab09002036de85f7041

**Comment by W3KIT-910** [comment]
Hello, 
Yes, I do have the new asl-statmon I got last night when it was 2 hours old.  I got it again just now to make sure but still initializing. 

Currently I have the allmon3.ini in 2 placed (/usr/local/etc/  and   /var/www/html/allmon3/api) otherwise the browser is throwing a fists with the parse error.

Also description is showing Unavailable (do I need privatenodes.txt somewhere? for local node and the link node is showing "NULL"

Wonder what any other dependencies do I need beside what were on the instructions.  I know I have to get JAVA installed since I did not have it install at first.  But not sure what else.

Here is my allmon3.ini minus password:

[547611]
ip=127.0.0.1
user=admin
pass=IAMNOTTELLING
monport=6750

[547613]
ip=127.0.0.1
user=admin
pass=IAMNOTTELLING
monport=6751

[547614]
ip=127.0.0.1
user=admin
pass=IAMNOTTELLING
monport=6752

[547615]
ip=127.0.0.1
user=admin
pass=IAMNOTTELLING
monport=6753




![Screenshot 2023-03-11 095959](https://user-images.githubusercontent.com/81514372/224491683-12a788a9-979b-4cd5-a358-e0820d2b909c.jpg)

**Comment by jxmx** [comment]
Stop the asl-statmon service and run it from a terminal with the `--debug` flag -- `/usr/local/bin/asl-statmon NODE /usr/local/etc/allmon3.ini --debug`. The look for something like this in the output and paste it here:

```
asl-statmon: DEBUG: command >> ACTION: RptStatus COMMAND: XStat NODE: 460182 ActionID: 14bfcc8b-1305-448e-aea1-9168cfecf372
asl-statmon: DEBUG: response >> ActionID: 14bfcc8b-1305-448e-aea1-9168cfecf372  Response: Success  Node: 460182  Conn: 48496     208.167.248.86      0           OUT        15:28:22            ESTABLISHED           LinkedNodes: T42130, T43211, T45839, T47735, T48496, T519551, T527250, T535070, T535151  Var: RPT_TXKEYED=0  Var: RPT_NUMLINKS=9  Var: RPT_LINKS=9,T48496,T43211,T47735,T45839,T535151,T42130,T519551,T527250,T535070  Var: RPT_NUMALINKS=1  Var: RPT_ALINKS=1,48496TU  Var: RPT_ETXKEYED=0  Var: RPT_RXKEYED=0  Var: RPT_AUTOPATCHUP=0  parrot_ena: 0  sys_ena: 0  tot_ena: 0  link_ena: 0  patch_ena: 0  patch_state: 4  sch_ena: 0  user_funs: 0  tail_type: 0  iconns: 0  tot_state: 2  ider_state: 2  tel_mode: 2

```

**Comment by jxmx** [comment]
Also, I can tell you don't have the latest web code running because of where that red dot is in the upper-right.

**Comment by W3KIT-910** [comment]
I saw that "red" dot last night moved to the center as well.  I thought I messed up the web php stuff. 

At any rate, I do have the red dot in the right place ( center?) at the moment.

![Screenshot 2](https://user-images.githubusercontent.com/81514372/224492471-6c5ffef1-2efe-4be0-8a94-7aa6cc6adca8.jpg)

**Comment by W3KIT-910** [comment]
asl-statmon: DEBUG: response >> ActionID: a52fe19e-2365-4373-9547-3ee3bae0322d  Response: Success  Node: 547611  Conn: 1910      127.0.0.1           0           OUT        135:04:17           ESTABLISHED           Conn: W3KIT     108.xx.xx.xxx       0           IN         00:30:43            ESTABLISHED           LinkedNodes: T1910, TW3KIT  Var: RPT_TXKEYED=0  Var: RPT_NUMLINKS=2  Var: RPT_LINKS=2,T1910,TW3KIT  Var: RPT_NUMALINKS=2  Var: RPT_ALINKS=2,1910TU,W3KITTU  Var: RPT_AUTOPATCHUP=0  Var: RPT_ETXKEYED=0  Var: RPT_RXKEYED=0  parrot_ena: 0  sys_ena: 1  tot_ena: 1  link_ena: 1  patch_ena: 1  patch_state: 4  sch_ena: 1  user_funs: 1  tail_type: 0  iconns: 1  tot_state: 2  ider_state: 2  tel_mode: 3

**Comment by jxmx** [comment]
What configuration are you using thathave a linked node named "W3KIT" and not a numeric node ID?

**Comment by W3KIT-910** [comment]
1910 = echolink 
547612 = SHARI UHF
W3KIT = IAX coming from DVSWITCH mobile app.

![Screenshot 3](https://user-images.githubusercontent.com/81514372/224494607-e7846541-6f64-4e36-b1de-5ba51cc9cea3.jpg)



![Screenshot 4](https://user-images.githubusercontent.com/81514372/224494611-c2157cd2-1bc3-4f1b-84d4-5e88b425633c.jpg)

**Comment by jxmx** [comment]
Continue this issue in #35
