### ISSUE TITLE
Support non-ASL IAX Connections

### ISSUE THREAD

**Issue by jxmx** [AllStarLink/Allmon3#35]
Reported in #34 that IAX-based connections that are ASL nodes coming in as a callsign and no modifier (like phone panel users). Support this.

**Comment by jxmx** [comment]
Please provide me with a single output of `asl-statmon-test-client.py` so I can see what your node is saying.

**Comment by W3KIT-910** [comment]
I am not sure exactly how to get the single output of the asl-statmon-test-client.py

How do I execute that command.

**Comment by jxmx** [comment]
`asl-statmon-test-client.py localhost 6750` assuming you're using defaults. Should get something like this:

```
$ asl-statmon-test-client.py localhost 6750
Creating 0MQ connection to localhost:6750
Connected. Press CTRL+c to stop...
460182
{"ME": 460182, "DESC": "KE8LDH 442.5125 MHz+ Norton", "RXKEYED": false, "TXKEYED": false, "TXEKEYED": false, "CONNKEYED": false, "CONNKEYEDNODE": false, "CONNS": {"48496": {"IP": "208.167.248.86", "DIR": "OUT", "CTIME": "18:50:51", "CSTATE": "ESTABLISHED", "PTT": "0", "SSK": "83", "SSU": "83", "MODE": "Transceive", "DESC": "W8WKY SARA Allstar Hub in the Cloud"}}}
460182
{"ME": 460182, "DESC": "KE8LDH 442.5125 MHz+ Norton", "RXKEYED": false, "TXKEYED": false, "TXEKEYED": false, "CONNKEYED": false, "CONNKEYEDNODE": false, "CONNS": {"48496": {"IP": "208.167.248.86", "DIR": "OUT", "CTIME": "18:50:52", "CSTATE": "ESTABLISHED", "PTT": "0", "SSK": "84", "SSU": "84", "MODE": "Transceive", "DESC": "W8WKY SARA Allstar Hub in the Cloud"}}}
^Cexiting on signal 2

```

**Comment by W3KIT-910** [comment]
`547611
{"ME": 547611, "DESC": "W3KIT  Silver Spring, MD USA", "RXKEYED": false, "TXKEYED": false, "TXEKEYED": false, "CONNKEYED": false, "CONNKEYEDNODE": false, "CONNS": {"1910": {"IP": "127.0.0.1", "DIR": "OUT", "CTIME": "139:24:31", "CSTATE": "ESTABLISHED", "PTT": "0", "SSK": "15305", "SSU": "15294", "MODE": "Transceive", "DESC": "Unavailable"}, "W3KIT": {"IP": null, "DIR": "0", "CTIME": "IN", "CSTATE": "04:50:57", "PTT": "0", "SSK": "5746", "SSU": "5739", "MODE": "Local Monitor", "DESC": null}, "547612": {"IP": "108.xx.xx.xxx", "DIR": "IN", "CTIME": "03:56:18", "CSTATE": "ESTABLISHED", "PTT": "0", "SSK": "4179", "SSU": "4178", "MODE": "Transceive", "DESC": "W3KIT 438.475 Silver Spring, MD USA"}}}
`

**Comment by jxmx** [comment]
Interesting. I need debug output of the command/response pair for the XStat output command. If you're running this as a daemon using systemctl then do the following:

1. Stop the instance of asl-statmon
2. Run a debug version -- `/usr/local/bin/asl-statmon NODE /usr/local/etc/allmon3.ini --debug`
3. LOTS of output will happen and keep happening. Break out of it after a few seconds.
4. Scroll back and find something that looks like this and paste it in here:

```
asl-statmon: DEBUG: starting the main work loop
asl-statmon: DEBUG: command >> ACTION: RptStatus COMMAND: XStat NODE: 48496 ActionID: e4baadd9-40af-4e3c-862c-f207828033aa
asl-statmon: DEBUG: response >> ActionID: e4baadd9-40af-4e3c-862c-f207828033aa  Response: Success  Node: 48496  Conn: 43211     66.219.164.130      5           OUT        51:33:23            ESTABLISHED           Conn: 535070    76.189.182.63       0           IN         185:10:06           ESTABLISHED           Conn: 527250    107.203.56.123      0           IN         56:49:07            ESTABLISHED           Conn: 460182    98.157.97.81        0           IN         23:40:44            ESTABLISHED           Conn: 519551    18.221.105.184      0           IN         09:21:08            ESTABLISHED           Conn: 54610     24.140.34.90        0           IN         01:24:56            ESTABLISHED           LinkedNodes: T43211, T45839, T460182, T47735, T519551, T527250, T535070, T54610  Var: RPT_TXKEYED=0  Var: RPT_NUMLINKS=8  Var: RPT_LINKS=8,T43211,T47735,T45839,T54610,T519551,T460182,T527250,T535070  Var: RPT_NUMALINKS=6  Var: RPT_ALINKS=6,43211TU,54610TU,519551TU,460182TU,527250TU,535070TU  Var: RPT_ETXKEYED=0  Var: RPT_RXKEYED=0  Var: RPT_AUTOPATCHUP=0  Var: TRANSFERCAPABILITY=SPEECH  parrot_ena: 0  sys_ena: 1  tot_ena: 1  link_ena: 1  patch_ena: 1  patch_state: 4  sch_ena: 1  user_funs: 1  tail_type: 0  iconns: 1  tot_state: 2  ider_state: 2  tel_mode: 1
asl-statmon: DEBUG: entering parse_xstat(48496)
asl-statmon: DEBUG: processed 6 connections
asl-statmon: DEBUG: exiting parse_xstat(48496)

```

**Comment by jxmx** [comment]
Obviously replace "NODE" with your node # above.

**Comment by jxmx** [comment]
And when you past it in here, please put three backticks before and after it so the formatting is preserved.

**Comment by W3KIT-910** [comment]
I do not know how much of the stuff you need.  If you need more I can capture more, there are sure a lot of stuffs.


```asl-statmon: DEBUG: starting the main work loop
asl-statmon: DEBUG: command >> ACTION: RptStatus COMMAND: XStat NODE: 547611 ActionID: 298b75b1-4c18-4609-8c6b-82de8149c1a0
asl-statmon: DEBUG: response >> ActionID: 298b75b1-4c18-4609-8c6b-82de8149c1a0  Response: Success  Node: 547611  Conn: 1910      127.0.0.1           0           OUT        141:46:12           ESTABLISHED           Conn: 547612    108.xx.xx.xxx       0           IN         06:17:59            ESTABLISHED           Conn: 3507690                       0           IN         00:00:08            ESTABLISHED           LinkedNodes: T1910, T3507690, T547612  Var: RPT_NUMLINKS=3  Var: RPT_LINKS=3,T1910,T3507690,T547612  Var: RPT_NUMALINKS=3  Var: RPT_ALINKS=3,1910TU,3507690TU,547612TU  Var: RPT_TXKEYED=0  Var: RPT_AUTOPATCHUP=0  Var: RPT_ETXKEYED=0  Var: RPT_RXKEYED=0  parrot_ena: 0  sys_ena: 1  tot_ena: 1  link_ena: 1  patch_ena: 1  patch_state: 4  sch_ena: 1  user_funs: 1  tail_type: 0  iconns: 1  tot_state: 2  ider_state: 2  tel_mode: 3
asl-statmon: DEBUG: entering parse_xstat(547611)
asl-statmon: DEBUG: enter get_echolink_name(507690)
asl-statmon: DEBUG: command >> ACTION: COMMAND COMMAND: echolink dbget nodename 507690 ActionID: 4a20fb22-be04-47cf-8123-c924ec27df5b
asl-statmon: DEBUG: response >> Response: Follows  Privilege: Command  ActionID: 4a20fb22-be04-47cf-8123-c924ec27df5b  507690|W3KIT|108.xx.xx.xxx
--END COMMAND--
```

**Comment by W3KIT-910** [comment]
I think everything is pretty much okay at this point,  registered nodes seem to display okay no problem.  Only local node < 1999 and IAX was the only issue.   If Allmon3 have the ability to read the privatenodes.txt like supermon it should display whatever was entered in the file.

Otherwise, allmon3 page looks really clean and pleasant, and I like it so far.   I have a question about the gear looking thing on the top right, what does it do?

![image](https://user-images.githubusercontent.com/81514372/224517720-0b965265-da98-455c-a5a1-f3af78c753b5.png)

**Comment by jxmx** [comment]
@W3KIT-910 how are you defining the IAX connection to your Asterisk host specifically?

Allmon3 is very much in a pre-beta state and things are changing very rapidly. Eventually the gear will pop up the management interface for that particular node. However it is not intending to track and/or necessarily mimic features from Supermon (or the older Allmon2). It's a ground-up rewrite. I definitely don't want to support reading in a .txt file if that's how Supermon does it. Maybe it'll make it something that can be defined in the web front end.

**Comment by jxmx** [comment]
Note to myself.... IAX-direct registrations look like Echolink connections but behave differently. I need to reconsider the processing of the `Conn:` entries in XStat to key off something other than ID format. Parsing arbitrary whitespace tables is obnoxious. 👎

**Comment by W3KIT-910** [comment]
I got in to the ASL using dvswitch for mobile. something like this..

![image](https://user-images.githubusercontent.com/81514372/224518874-d20d676b-af0e-41d0-8c29-7cbbfe6e3feb.png)

On the ASL node I just assigned username and password in the iax.conf and that about it.

**Comment by jxmx** [comment]
Try this: 00c1611
Otherwise, I'll have to setup an IAX direct connection for further testing. If you still get errors or it crashes please provide the `--debug` output.

**Comment by W3KIT-910** [comment]
I do not encounter an error or any crashes, all seems okay.  For locals and private node just limited to "Direct Client and/or Private or Unavailable" as those cannot be customized.

![image](https://user-images.githubusercontent.com/81514372/224572748-751f64d4-d689-48d5-b763-41ac110dc87a.png)

**Comment by jxmx** [comment]
Terrific!  I've opened an enhancement in #38 to potentially address a custom front-end label in the future. I don't want to do it at the data-broker level because that may not be desired by all consumers of the message bus.
