### ISSUE TITLE
Provide URL for selected Node or Nodes

### ISSUE THREAD

**Issue by tsawyer** [AllStarLink/Allmon3#39]
Would like to see a URL that can be bookmarked for one or more nodes.

For example https://myallmon3.com/1234,1235 or https://myallmon3.com?nodes=1234,1235

**Comment by jxmx** [comment]
[92ab2cb](https://github.com/AllStarLink/Allmon3/commit/92ab2cb018456fa99171ddd01d9811bcad021301)

index.html now takes ?n=NODE[,NODE,....]

**Comment by tsawyer** [comment]
When clicking a node on the left, the URL continues to show the URI query.  
<img width="1192" alt="Screenshot 2023-03-13 at 8 06 35 AM" src="https://user-images.githubusercontent.com/1526362/224744895-7b02d1b0-fad7-40a8-a22c-ec5261dd00c9.png">

**Comment by jxmx** [comment]
01885fc..5e2c933
