### ISSUE TITLE
"Local Monitor" Mode for Direct Connect

### ISSUE THREAD

**Issue by tsawyer** [AllStarLink/Allmon3#44]
**Describe the bug**
Mode is wrong for Direct connect from Radiotelephone iOS client. 
**To Reproduce**
Connect with Radiotelephone
**Expected behavior**
Should show "Transceive"
**Screenshots**
Done

**Version Info**
DEVELOPMENT BUILD
20230315-00
<img width="987" alt="Screenshot 2023-03-16 at 12 37 25 PM" src="https://user-images.githubusercontent.com/1526362/225735149-f1d2df79-994b-445d-bd61-1bff67a78722.png">
<img width="819" alt="Screenshot 2023-03-16 at 12 38 07 PM" src="https://user-images.githubusercontent.com/1526362/225735176-874615f6-adfc-4514-b1fe-8fdfc0890839.png">

**Comment by jxmx** [comment]
@tsawyer - Are these IAX2-direct connections? I need to know how to reproduce this.

**Comment by tsawyer** [comment]
The screenshots show a connect from the MacOS app "Transceive"., https://apps.apple.com/us/app/transceive/id1529395199?mt=12

The arrows are misleading as node 25333 has nothing to do with the issue. The issue is that Allmon3 is showing Local Monitor when it should show Transceive as on Allmon2.

Best way to reproduce this is for me to connect to your node so you can look at the data.

**Comment by jxmx** [comment]
f446887..c466dbb
