### ISSUE TITLE
Private Node Not Responding

### ISSUE THREAD

**Issue by tsawyer** [AllStarLink/Allmon3#46]
**Describe the bug**
Title says it all.

**To Reproduce**
Click https://wd6awp.net/allmon3/index.html?n=501

**Screenshots**
<img width="992" alt="Screenshot 2023-03-18 at 2 35 18 PM" src="https://user-images.githubusercontent.com/1526362/226141378-ba1e369d-47bf-4df5-b43b-9c01c0f9633c.png">

**Version Info**
20230318-00

**Comment by jxmx** [comment]
Do you have a running asl-statmon process for a three digit node? I'm pretty sure it won't start unless the node number is >= 1000. There's a check in there for a node number within a rationally-sized integer.

**Comment by jxmx** [comment]
```
$ asl-statmon 500 /usr/local/etc/allmon3.ini
asl-statmon: ERROR: provided node "500" must be a number between 1000 and 9999999
```

I didn't think nodes could be less than 4 digits?

**Comment by tsawyer** [comment]
Recommended not less than 4 but not required. See https://wiki.allstarlink.org/wiki/Private_nodes

**Comment by jxmx** [comment]
ok. Updating this title accordingly.

**Comment by jxmx** [comment]
1742549..921a45f
