### ISSUE TITLE
Block various command modals when not logged in

### ISSUE THREAD

**Issue by tsawyer** [AllStarLink/Allmon3#58]
The login/logout is not reflecting the actual status. Also notice the button disappears. Hopefully you can tell from the video what is going on. 

https://user-images.githubusercontent.com/1526362/226979978-28267840-0502-4f42-ace2-a931b8bd9068.mp4

**Comment by jxmx** [comment]
@tsawyer what happened before you tried to make the connection? Are you able to cause that to happen from a fresh browser start?

**Comment by jxmx** [comment]
Also what browser?

**Comment by tsawyer** [comment]
I think some of this issue was caused by, or maybe resulted in, the asl-cmdlink service failing. Would have the command dialog display a banner if not logged in on the service not running help?

**Comment by tsawyer** [comment]
> @tsawyer what happened before you tried to make the connection? 

Unknown.

>  Are you able to cause that to happen from a fresh browser start?

No. A fresh reload of the page after starting the asl-cmdlink service clears up the issue.

**Comment by jxmx** [comment]
That would not be related. You didn't get to a part where it tried to talk to a `asl-cmdlink` service. You can see your authentication status by browsing directly to `/api/session-handler.php` and `/api/session-check.php`

**Comment by tsawyer** [comment]
> Also what browser?

Safari on the latest Ventura OS.

**Comment by jxmx** [comment]
If you don't have a session the label on the API response will be "SECURITY". If it had an actual back-end error talking to asl-cmdlink it would be "ERROR".

**Comment by jxmx** [comment]
> > Also what browser?
> 
> Safari on the latest Ventura OS.

I don't have a Mac so I can't test Safari. Can you try in Firefox or Chrome/Chromium? I can't replicate that at all with Firefox or Edge(Chrome).

**Comment by tsawyer** [comment]
Currently, with normal operation:

`https://wd6awp.net/allmon3/api/session-handler.php` returns a blank page.

`https://wd6awp.net/allmon3/api/session-check.php` returns `{ "SUCCESS" : "OK" }`

**Comment by jxmx** [comment]
And I get what I expect:
![image](https://user-images.githubusercontent.com/21324335/226985789-6196d2d9-81cf-439d-846c-b7b646e455dd.png)

The logon box should be toggled by the status of `session-check.php`. The only bug I can think of is if one of the "onclick" event hooks doesn't get fired properly in Safari.

**Comment by tsawyer** [comment]
> > > Also what browser?
> > 
> > 
> > Safari on the latest Ventura OS.
> 
> I don't have a Mac so I can't test Safari. Can you try in Firefox or Chrome/Chromium? I can't replicate that at all with Firefox or Edge(Chrome).

I can't duplicate it with Safari, cmdlink fails for unknown reason. 

For me, even with cmdlink stopped, the Link dialog comes up. I would think if either I'm not logged in or cmdlink is not running that should not happen.

**Comment by jxmx** [comment]
At the moment, there is no active checking of the command dialog boxes. It's a feature that needs to be added. Just haven't done it yet.

**Comment by tsawyer** [comment]
> And I get what I expect: ![image](https://user-images.githubusercontent.com/21324335/226985789-6196d2d9-81cf-439d-846c-b7b646e455dd.png)
> 
> The logon box should be toggled by the status of `session-check.php`. The only bug I can think of is if one of the "onclick" event hooks doesn't get fired properly in Safari.

Yes, same response here. However the Link dialog comes up when not logged in.

**Comment by tsawyer** [comment]
> At the moment, there is no active checking of the command dialog boxes. It's a feature that needs to be added. Just haven't done it yet.

Ok, I'm ahead of myself again.

**Comment by tsawyer** [comment]
Perhaps this from `journalctl -u asl-cmdlink@2509.service` is helpful.  

```
Mar 19 15:31:01 ip-172-26-12-227 asl-cmdlink[15337]: asl-cmdlink: ERROR: asl_cmd_response() BrokenPipeError
Mar 19 15:31:01 ip-172-26-12-227 asl-cmdlink[15337]: asl-cmdlink: ERROR: asl_cmd() exception <class 'BrokenPipeError'>
Mar 19 15:31:01 ip-172-26-12-227 asl-cmdlink[15337]: asl-cmdlink: ERROR: asl_cmd() message <class 'BrokenPipeError'>
Mar 19 15:31:01 ip-172-26-12-227 asl-cmdlink[15337]: asl-cmdlink: ERROR: received BrokenPipeError; trying to reconnect
Mar 19 15:31:17 ip-172-26-12-227 asl-cmdlink[15337]: asl-cmdlink: INFO: connection reestablished after 1 retries
Mar 19 15:31:17 ip-172-26-12-227 asl-cmdlink[15337]: asl-cmdlink: ERROR: Operation cannot be accomplished in current state
Mar 19 15:31:17 ip-172-26-12-227 asl-cmdlink[15337]: Traceback (most recent call last):
Mar 19 15:31:17 ip-172-26-12-227 asl-cmdlink[15337]:   File "/usr/local/bin/asl-cmdlink", line 383, in <module>
```

I can't reproduce this on demand but it seems to occur when app_rpt is producing error messages
```
Exceptionally long voice queue length queuing to
```
from testing failures.

**Comment by jxmx** [comment]
They definitely aren't related. But that issue above deserves a separate bug report.

**Comment by jxmx** [comment]
39ad242..3b8477f
