### ISSUE TITLE
But I am logged in

### ISSUE THREAD

**Issue by tsawyer** [AllStarLink/Allmon3#60]
What more can I tell you?
<img width="1336" alt="Screenshot 2023-03-22 at 4 06 47 PM" src="https://user-images.githubusercontent.com/1526362/227058981-b119898f-8e4c-44ec-a76d-8ead36ba7ecb.png">

**Comment by jxmx** [comment]
I think I fixed that right before I ran out to the store here… Make sure you pull down the absolute latest command.JS.

On Mar 22, 2023, at 7:15 PM, Tim Sawyer ***@***.***> wrote:

﻿

What more can I tell you?
[Screenshot 2023-03-22 at 4 06 47 PM]<https://user-images.githubusercontent.com/1526362/227058981-b119898f-8e4c-44ec-a76d-8ead36ba7ecb.png>

**Comment by jxmx** [comment]
And functions.is

On Mar 22, 2023, at 7:15 PM, Tim Sawyer ***@***.***> wrote:

﻿

What more can I tell you?
[Screenshot 2023-03-22 at 4 06 47 PM]<https://user-images.githubusercontent.com/1526362/227058981-b119898f-8e4c-44ec-a76d-8ead36ba7ecb.png>
