### ISSUE TITLE
URI in Menu

### ISSUE THREAD

**Issue by tsawyer** [AllStarLink/Allmon3#68]
This example URI causes the menu to disappear. Removing the `?n=2510,2530` restores the menu but doesn't display the desired result, obviously. 

```
[ both ]
type = single
AWP Hubs = https://wd6awp.net/allmon3/index.html?n=2510,2530
```

**Comment by jxmx** [comment]
You have to enclose the value in single quotes:

```
AWP Hubs = 'https://wd6awp.net/allmon3/index.html?n=2510,2530'
```

That's how PHP's INI processor works. I probably should put a note about that in the example .ini

**Comment by tsawyer** [comment]
That works, thanks. I should have trued that.
