### ISSUE TITLE
Specify Node Number on CLI and INI

### ISSUE THREAD

**Issue by tsawyer** [AllStarLink/Allmon3#7]
Why is the node number specified both on the command line and in the ini file? I wonder if it possible to use only the ini file. For example my test node .ini might look like:

```
ip=localhost
user=admin
pass=xxxxxxxxx
monport=6750
nodes=2509,25334
```

**Comment by jxmx** [comment]
My intention was to have one .ini just like allmon.ini now and just add the additional attributes that asl-statmon needs. I was going to create a manager script that starts by-instance damons based on node entries in the ini file so the asl-statmon program itself needs to know which node it is. I was trying to make it simple and only have one place to define nodes but it definitely makes the downstream logic more complicated.

**Comment by tsawyer** [comment]
That makes sense. Sounds like you're thinking what I am. So what is the node number on the command line for?
```
./asl-statmon
usage: asl-statmon [-h] [--debug] node config  
```

**Comment by jxmx** [comment]
If you take a hypothetical three-node Allmon. In allmon.ini there would be three nodes defined, each with their own section. So...

```
[2000]
...

[2001]
...

[2002]
...
```

Then you would launch each process with something like `systemctl start asl-statmon@2000`, `systemctl start asl-statmon@2001`, etc. Effectively that would be doing something like:

```
./asl-statmon 2000 /var/www/html/allmon.ini
./asl-statmon 2001 /var/www/html/allmon.ini
./asl-statmon 2002 /var/www/html/allmon.ini
```

At the end of the day though, asl-statmon needs to be told which node it "is".
